// src/apps/photo-companion-solid/src/routes/bridges/components/card-bridge/card-bridge-sparkline.tsx
import { round } from "utils/math";

import { formatTimeShort } from "@stores/lang";
import { getDate } from "@lib/helpers";
import { createWavyPath } from "@lib/helpers/svg";
import styles from "./card-bridge.module.css";

import { mergeProps, For } from "solid-js";
import type { BridgeSparklineProps, ScheduleEntry, SparklineProps, TimeProps, WaterPathProps } from "./card-bridge.types";
import { DEFAULT_PROPS_SPARKLINE } from "./card-bridge.const";
import { buildBridgeSparklinePath } from "./card-bridge.utils";

const Sparkline = (props: SparklineProps) => (
	<path
		d={buildBridgeSparklinePath(props)}
		stroke-linecap="round"
		fill="none"
	/>
);

const Time = (props: TimeProps) => (
	<text
		x={props.x}
		y={props.y}
		font-size={props.fontSize.toString()}
		fill="white"
	>
		{formatTimeShort(props.date)}
		<title>
			{formatTimeShort(props.date)}
		</title>
	</text>
);

const WaterPath = (props: WaterPathProps) => (
	<path
		data-stroke-water
		d={createWavyPath(`M ${props.x1 + 6},0 L ${props.x2 - 6},${0}`, 5, 2)}
		stroke-linecap="round"
		fill="none"
	/>
);

function SparklineEntry(props: ScheduleEntry) {
	const x1 = () => props.hoursStart * 60 + props.minutesStart;
	const x2 = () => props.hoursEnd * 60 + props.minutesEnd;
	const dateStart = () => getDate({
		hours: props.hoursStart,
		minutes: props.minutesStart,
		seconds: 0
	});
	const dateEnd = () => getDate({
		hours: props.hoursEnd,
		minutes: props.minutesEnd,
		seconds: 0
	});

	return (
		<>
			<WaterPath x1={x1()} x2={x2()} />
			<Time
				x={x1() - props.fontSize}
				y={props.fontSize * 1.5}
				fontSize={props.fontSize}
				date={dateStart()}
			/>
			<Time
				x={x2() - props.fontSize}
				y={props.fontSize * 1.5}
				fontSize={props.fontSize}
				date={dateEnd()}
			/>
		</>
	);
}

export function BridgeSparkline(allProps: BridgeSparklineProps) {
	const props = mergeProps(DEFAULT_PROPS_SPARKLINE, allProps);

	const dx = () => round(props.length * Math.cos(props.angle), 2);
	const dy = () => round(props.length * Math.sin(props.angle));
	const viewBox = () => `${props.start * 60} -${dy()} ${(props.end - props.start) * 60} ${dy() + props.stroke + props.fontSize * 2}`;

	return (
		<svg
			class={styles.sparkline}
			style={{
				"--sparkline-stroke-width": props.strokeWidth
			}}
			viewBox={viewBox()}
		>
			<Sparkline
				schedule={props.schedule}
				dx={dx()}
				dy={dy()}
				start={props.start}
				end={props.end}
			/>
			<For each={props.schedule}>
				{([ hoursStart, minutesStart, hoursEnd, minutesEnd ]) => (
					<SparklineEntry
						hoursStart={hoursStart}
						minutesStart={minutesStart}
						hoursEnd={hoursEnd}
						minutesEnd={minutesEnd}
						fontSize={props.fontSize}
					/>
				)}
			</For>
		</svg>
	);
}

// src/apps/photo-companion/src/lib/components/card-bridge/card-bridge-sparkline.svelte
<script lang="ts">
	import { round } from "utils/math";

	import { formatTimeShort } from "@stores/lang";
	import { getDate } from "@lib/helpers";
	import { createWavyPath } from "@lib/helpers/svg";
	import type { BridgeScheduleEntry } from "bridge-schedule";
	import styles from "./card-bridge.module.css";

	export let schedule: BridgeScheduleEntry;
	export let start = 1;
	export let end = 6;
	export let angle = Math.PI / 4;
	export let length = 25;
	export let stroke = 0.5;
	export let fontSize = 5;

	let dx = round(length * Math.cos(angle), 2);
	let dy = round(length * Math.sin(angle));
	let viewBox = `${start * 60} -${dy} ${(end - start) * 60} ${dy + stroke + fontSize * 2}`;

	const buildBridgeSparklinePath = (schedule: BridgeScheduleEntry): string => {
		let x = start * 60;
		let y = 0;

		const pathElements: string[] = [ `M ${x},${y}` ];

		for (const [ hoursStart, minutesStart, hoursEnd, minutesEnd ] of schedule) {
			x = hoursStart * 60 + minutesStart;
			pathElements.push(`L ${x},${y}`);

			x += dx;
			y -= dy;
			pathElements.push(`L ${x},${y}`);

			x = hoursEnd * 60 + minutesEnd - dx;
			pathElements.push(`M ${x},${y}`);

			x += dx;
			y = 0;
			pathElements.push(`L ${x},${y}`);
		}

		x = end * 60;
		pathElements.push(`L ${x},${y}`);

		return pathElements.join(" ");
	};
</script>

<svg
	class="{styles.sparkline}"
	{viewBox}
>
	<path
		d="{buildBridgeSparklinePath(schedule)}"
		stroke-width="{stroke}"
		stroke-linecap="round"
		fill="none"
	/>
	{#each schedule as [ hoursStart, minutesStart, hoursEnd, minutesEnd ]}
		{@const x1 = hoursStart * 60 + minutesStart}
		{@const x2 = hoursEnd * 60 + minutesEnd}
		{@const dateStart = getDate({ hours: hoursStart, minutes: minutesStart, seconds: 0 })}
		{@const dateEnd = getDate({ hours: hoursEnd, minutes: minutesEnd, seconds: 0 })}
		<path
			data-stroke-water
			d="{createWavyPath(`M ${x1 + 6},0 L ${x2 - 6},${0}`, 5, 2)}"
			stroke-width="{stroke}"
			stroke-linecap="round"
			fill="none"
		/>
		<text
			x="{x1 - fontSize}"
			y="{fontSize * 1.5}"
			font-size="{fontSize}"
			fill="white"
		>
			{formatTimeShort(dateStart)}
			<title>
				{formatTimeShort(dateStart)}
			</title>
		</text>
		<text
			x="{x2 - fontSize}"
			y="{fontSize * 1.5}"
			font-size="{fontSize}"
			fill="white"
		>
			{formatTimeShort(dateEnd)}
			<title>
				{formatTimeShort(dateEnd)}
			</title>
		</text>
	{/each}
</svg>
