// src/lib/components/moon/moon.svelte
<script lang="ts">
	import { tweened } from "svelte/motion";
	import styles from "./moon.module.css";

	export let phase = 0;
	export let rotation = 0;
	export let size = 100;
	export let radius = size / 2 - 5;
	export let precision = 0.025;

	let center = size / 2;
	const phaseTweened = tweened(phase);

	const getNormalizedPhase = (phase: number) => {
		return phase <= 0.5
			? phase
			: 1 - phase;
	};

	const getNormalizedAngleRad = (phase: number) => {
		const norm = getNormalizedPhase(phase);
		const radians = (Math.PI * norm) / 0.5;
		return radians;
	};

	$: void phaseTweened.set(phase);
</script>

<svg
	class="{styles.moon}"
	viewBox="0 0 {size} {size}"
	style="
		--moon-disk-angle: {getNormalizedAngleRad($phaseTweened)}rad;
		transform: rotate({-rotation}rad);
	"
>
	<circle
		class="{styles.shadow}"
		cx="{center}"
		cy="{center}"
		r="{radius}"
	/>
	<circle
		class="{styles.semicircle}"
		class:visible="{$phaseTweened >= 0.5 && $phaseTweened < 1 - precision}"
		data-left
		cx="{center}"
		cy="{center}"
		r="{radius}"
	/>
	<circle
		class="{styles.semicircle}"
		class:visible="{$phaseTweened <= 0.5 && $phaseTweened >= precision}"
		data-right
		cx="{center}"
		cy="{center}"
		r="{radius}"
	/>
	<circle
		class="{styles.diff}"
		class:dark="{0.5 / getNormalizedPhase($phaseTweened) > 2}"
		cx="{center}"
		cy="{center}"
		r="{radius}"
	/>
</svg>

// src/apps/photo-companion-solid/src/lib/components/moon/moon.tsx
import { mergeProps } from "solid-js";
import { createTweened } from "ui-solid/primitives";

import { DEFAULT_PROPS } from "./moon.const";
import { getNormalizedAngleRad, getNormalizedPhase } from "./moon.helpers";

import type { CircleCommonProps, CircleProps, MoonProps } from "./moon.types";

import styles from "./moon.module.css";

export function createCircle(commonProps: CircleCommonProps) {
	return (props: CircleProps) => (
		<circle {...commonProps} {...props} />
	);
}

export function Moon(allProps: MoonProps) {
	const props = mergeProps(DEFAULT_PROPS, allProps);
	const phase = createTweened(() => props.phase);

	const viewBox = () => `0 0 ${props.size} ${props.size}`;
	const center = () => props.size / 2;
	const radius = () => props.size / 2 - 10;

	const visibleLeft = () => phase() >= 0.5 && phase() < 1 - props.precision;
	const visibleRight = () => phase() <= 0.5 && phase() >= props.precision;
	const dark = () => 0.5 / getNormalizedPhase(phase()) > 2;

	const Circle = createCircle({
		cx: center(),
		cy: center(),
		r: radius()
	});

	return (
		<svg
			class={styles.moon}
			style={{
				"--moon-disk-angle": `${getNormalizedAngleRad(phase())}rad`,
				"--moon-rotation": `${props.rotation}deg`,
				"transform": `rotate(${props.rotation}deg)`
			}}
			viewBox={viewBox()}
		>
			<Circle class={styles.shadow} />
			<Circle
				class={styles.semicircle}
				classList={{
					[styles.visible]: visibleLeft()
				}}
				data-left
			/>
			<Circle
				class={styles.semicircle}
				classList={{
					[styles.visible]: visibleRight()
				}}
				data-right
			/>
			<Circle
				class={styles.diff}
				classList={{
					[styles.dark]: dark()
				}}
			/>
		</svg>
	);
}
