// src/apps/photo-companion/src/lib/layout/with-date/with-date.svelte
<script lang="ts">
	import { query } from "svelte-pathfinder";
	import { InputDatetime } from "ui";
	import { isValidDate } from "utils/validators";

	import ErrorDate from "../../../pages/error-date/error-date.svelte";
	import { parseQueryDate, createQueryDate } from "@lib/helpers";
	import { onMount } from "svelte";
	import styles from "./with-date.module.css";
	import { dict } from "@lib/dict";

	let value = parseQueryDate($query.date as string);
	let date = new Date(value);

	const handleChange = (event: CustomEvent<{ value: string }>) => {
		date = new Date(event.detail.value);
		$query.date = createQueryDate(date);
	};

	query.hook(($updated) => {
		if (!$updated) {
			return false;
		}

		value = parseQueryDate($updated.date as string);
		date = new Date(value);
	});

	onMount(() => {
		if (!$query.date) {
			$query.date = createQueryDate();
		}
	});
</script>

{#if !isValidDate(date)}
	<ErrorDate />
{:else}
	<slot {date} />
{/if}

<InputDatetime
	className="{styles["date-input"]}"
	dict="{{
		DATETIME: dict.LABEL.DATETIME,
		NEXT_DAY: dict.LABEL.NEXT_DAY,
		PREVIOUS_DAY: dict.LABEL.PREVIOUS_DAY
	}}"
	on:datechange="{handleChange}"
	{value}
/>

// src/apps/photo-companion-solid/src/lib/layout/with-date/with-date.tsx
import { useSearchParams } from "@solidjs/router";
import { createSignal, onMount, type ParentProps } from "solid-js";
import { InputDatetime } from "ui-solid";

import { t } from "@stores/lang";
import { parseQueryDate, createQueryDate, getDateTimeString } from "@lib/helpers";
import styles from "./with-date.module.css";
import { isNullable } from "utils/validators";

export function WithDate(props: ParentProps) {
	const [ query, setQuery ] = useSearchParams();
	const [ value, setValue ] = createSignal<string>(getDateTimeString());

	const dict = () => {
		const translation = t();

		return {
			DATETIME: translation.LABEL.DATETIME,
			NEXT_DAY: translation.LABEL.NEXT_DAY,
			PREVIOUS_DAY: translation.LABEL.PREVIOUS_DAY,
			NOW: translation.LABEL.NOW
		};
	};

	const setDateQuery = (input?: Date): void => {
		setQuery({
			date: createQueryDate(input)
		});
	};

	const handleDatetimeChange = (input: string) => {
		setValue(input);
		setDateQuery(new Date(value()));
	};

	onMount(() => {
		if (isNullable(query.date)) {
			setDateQuery();
			setValue(getDateTimeString());
		} else {
			const parsed = parseQueryDate(query.date);
			setValue(getDateTimeString(parsed));
		}
	});

	return (
		<>
			{props.children}
			<InputDatetime
				class={styles["date-input"]}
				dict={dict()}
				onDatetimeChange={handleDatetimeChange}
				value={value()}
			/>
		</>
	);
}
