// src/apps/photo-companion/src/lib/components/input-select/input-select.svelte
<script lang="ts" context="module">
	export interface InputSelectOption {
		disabled?: boolean,
		label: string;
		value: string;
		selected?: boolean;
	}
</script>

<script lang="ts">
	import styles from "./input-select.module.css";

	export let disabled = false;
	export let name: string;
	export let options: InputSelectOption[];
	export let value: string | undefined = undefined;

	if (!value) {
		value = options.find(item => Boolean(item.selected))?.value;
	}
</script>

<label class="{styles.wrapper}">
	<slot />
	<select
		bind:value
		class="{styles.select}"
		{disabled}
		{name}
		on:change
	>
		{#each options as { disabled, value, label, selected }}
			<option {value} {selected} {disabled}>
				{label}
			</option>
		{/each}
	</select>
</label>

// packages/photo-companion/src/shared/ui/input-select/input-select.tsx
import { For, type JSX, splitProps } from "solid-js";
import { classnames } from "utils";

import type { Classes } from "../../types";

import styles from "./input-select.module.css";

export interface InputSelectOption {
	disabled?: boolean,
	label: string;
	selected?: boolean;
	value: string;
}

export interface InputSelectProps extends Omit<JSX.InputHTMLAttributes<HTMLSelectElement>, "class"> {
	classes?: Classes<"label" | "option" | "select">;
	label?: string;
	options: InputSelectOption[];
}

export function InputSelect(allProps: InputSelectProps) {
	const [ props, rest ] = splitProps(allProps, [ "classes", "children", "options" ]);

	return (
		<label class={classnames(styles.label, props.classes?.label)}>
			{props.children}
			<select class={classnames(styles.select, props.classes?.select)} {...rest}>
				<For each={props.options}>
					{({ label, ...other }) => (
						<option class={props.classes?.option} {...other}>
							{label}
						</option>
					)}
				</For>
			</select>
		</label>
	);
}
