// src/core/ui/src/components/link/link.tsx
import { type JSX, splitProps } from "solid-js";
import { classnames } from "utils";
import { isNonEmptyString, isNullable } from "utils/validators";

import styles from "./link.module.css";

export interface LinkProps extends JSX.AnchorHTMLAttributes<HTMLAnchorElement> {
	block?: boolean;
	nofollow?: boolean;
	query?: string | URLSearchParams;
}

export function Link(allProps: LinkProps) {
	const [ props, rest ] = splitProps(allProps, [
		"class",
		"children",
		"href",
		"nofollow",
		"target",
		"query"
	]);

	const href = () => {
		if (isNullable(props.query)) {
			return props.href;
		}

		if (isNonEmptyString(props.query)) {
			return `${props.href}${props.query}`;
		}

		return `${props.href}?${props.query.toString()}`;
	};

	const external = () => Boolean(props.href?.includes("://"));
	const target = () => (props.target !== "_blank" && external()) ? "_blank" : undefined;

	const rel = () => classnames(
		external() && "noopener noreferrer",
		props.nofollow && "nofollow"
	);

	return (
		<a
			class={classnames(styles.link, props.class)}
			data-external={external() ? "" : undefined}
			href={href()}
			rel={rel()}
			target={target()}
			{...rest}
		>
			{props.children}
		</a>
	);
}

// src/deprecated/ui-svelte/src/components/link/Link.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./link.module.css";

	export let block = false;
	export let className: Undefinable<string> = undefined;
	export let current: Undefinable<"page" | "step" | "location" | "date" | "time"> = undefined;
	export let download: undefined | string = undefined;
	export let href: string;
	export let label: Undefinable<string> = undefined;
	export let targetBlank = false;
	export let nofollow = false;
	export let title: Undefinable<string> = undefined;

	let ref: Nullish<HTMLAnchorElement> = null;

	// if no `href` is provided -> link will be disabled
	$: external = href.indexOf("://") !== -1;
	$: target = (targetBlank || external) ? "_blank" : undefined;
	$: rel = `${external ? "noopener noreferrer" : ""}` + `${nofollow ? "nofollow" : ""}`;
</script>

<a
	bind:this="{ref}"
	class="{classnames(styles.link, className)}"
	class:block
	aria-current="{current}"
	aria-label="{label}"
	{download}
	{href}
	on:click
	{rel}
	{target}
	{title}
	{...$$restProps}
>
	<slot />
</a>
