// src/deprecated/photo-companion-svelte/src/lib/components/gauge/gauge-pointer.svelte
<svelte:options namespace="svg" />

<script lang="ts">
	import { setAttribute } from "@lib/helpers";
	import styles from "./gauge.module.css";

	export let active: boolean;
	export let cx: number | string;
	export let cy: number | string;
	export let radius: number;
	export let angle: number;
</script>

<circle
	class="{styles.pointer}"
	{cx}
	{cy}
	r="{radius}"
	data-active="{setAttribute(active)}"
	style="--gauge-pointer-angle: {angle}deg;"
/>

// src/apps/photo-companion-solid/src/lib/components/gauge/gauge-pointer.tsx
import { splitProps, type JSX } from "solid-js";

import { setAttribute } from "../../helpers";
import styles from "./gauge.module.css";

interface Props extends JSX.SvgSVGAttributes<SVGCircleElement> {
	active: boolean;
	angle: number;
	cx: number;
	cy: number;
	r: number;
}

export function Pointer(allProps: Props) {
	const [ props, rest ] = splitProps(allProps, [
		"active",
		"angle"
	]);

	return (
		<circle
			class={styles.pointer}
			data-active={setAttribute(props.active)}
			style={{
				"--gauge-pointer-angle": `${props.angle}deg`
			}}
			{...rest}
		/>
	);
}
