// src/apps/photo-companion/src/routes/settings/settings.page.tsx
import { createStore, unwrap } from "solid-js/store";
import { Button, Fieldset, Form, InputRadio } from "ui";

import { SETTINGS_DEFAULT, useSettings, useTranslation } from "@lib/context";

import { InputEventFilters, InputGeolocation, InputTabsSelect } from "./components";
import { LANGUAGE_OPTIONS, LIGHTS_CITY_OPTIONS } from "./settings.const";

import styles from "./settings.module.css";

export function PageSettings() {
	const { t } = useTranslation();
	const { getSettings, resetSettings, setSettings } = useSettings();
	const [ store, setStore ] = createStore(getSettings());

	const handleChange = (event: Event) => {
		const target = event.target as HTMLInputElement;
		const { name, value } = target;

		switch (name) {
			case "language":
			case "lights_city": {
				setStore({ [name]: value });
				break;
			}
			case "latitude":
			case "longitude": {
				setStore({ [name]: Number(value) });
				break;
			}
		}
	};

	const handleSubmit = () => {
		setSettings({ ...unwrap(store) });
	};

	const handleReset = () => {
		setStore(SETTINGS_DEFAULT);
		resetSettings();
	};

	return (
		<div class={styles.page}>
			<h2>{t().TITLE.SETTINGS}</h2>
			<Form onChange={handleChange}>
				<Fieldset legend={t().LABEL.LANGUAGE}>
					<InputRadio
						name="language"
						options={LANGUAGE_OPTIONS}
						value={store.language}
					/>
				</Fieldset>
				<Fieldset legend={t().LABEL.GEOLOCATION}>
					<InputGeolocation
						setStore={setStore}
						store={store}
					/>
				</Fieldset>
				<Fieldset legend={t().LABEL.TABS}>
					<aside>
						{t().MESSAGE.TAB_LIMITS}
					</aside>
					<InputTabsSelect
						initialTabs={store.tabs}
						name="tabs"
						onChange={(name, value) => setStore({ [name]: value })}
					/>
				</Fieldset>
				<Fieldset legend={t().LABEL.LIGHTS_CITY}>
					<InputRadio
						name="lights_city"
						options={LIGHTS_CITY_OPTIONS(t())}
						value={store.lights_city}
					/>
				</Fieldset>
				<Fieldset legend={t().LABEL.EVENT_ALLOW_LIST}>
					<InputEventFilters
						onChange={(name, value) => setStore({ [name]: value })}
						store={store}
					/>
				</Fieldset>
				<Fieldset class={styles.submit}>
					<Button
						appearance="outline"
						color="success"
						onClick={handleSubmit}
						variant="success"
					>
						{t().LABEL.SAVE}
					</Button>
					<Button
						appearance="outline"
						onClick={handleReset}
					>
						{t().LABEL.RESET}
					</Button>
				</Fieldset>
			</Form>
		</div>
	);
}

export default PageSettings;

// src/apps/photo-companion/src/pages/settings/settings.page.svelte
<script lang="ts">
	import {
		Button,
		Form,
		Fieldset,
		InputNumber,
		InputRadio,
		type Option
	} from "@lib/components";
	import GeolocationButton from "./geolocation-button.svelte";
	import { settingsStore } from "@lib/settings-store";
	import { dict } from "@lib/dict";
	import { lightsCityList } from "@lib/constants";

	import styles from "./settings.module.css";
	import type { LightsCity } from "@shared/types";

	let settings = settingsStore.get();

	const handlePersist = () => {
		settingsStore.set(settings);
	};

	const handleReset = () => {
		settingsStore.reset();
		settings = settingsStore.get();
	};

	const LIGHTS_CITY_OPTIONS: Option[] = [
		{ label: dict["off"], value: "" },
		...lightsCityList.map(item => ({ label: dict[item], value: item }))
	];

	const handleChange = (event: Event) => {
		const target = event.target as HTMLInputElement;
		const { name, value } = target;

		switch (name) {
			case "latitude": {
				settings.lat = Number(value);
				break;
			}
			case "longitude": {
				settings.lon = Number(value);
				break;
			}
			case "lights-city": {
				if (value) {
					settings["lights-city"] = value as LightsCity;
				} else {
					settings["lights-city"] = null;
				}
			}
		}
	};
</script>

<div class="{styles.page}">
	<h2>{dict["settings"]}</h2>
	<Form on:submit="{handlePersist}" on:change={handleChange}>
		<Fieldset legend="{dict["geoposition"]}">
			<InputNumber
				min={-90}
				max={90}
				name="latitude"
				step="{0.000001}"
				inputmode="numeric"
				value="{settings.lat}"
			>
				{dict["latitude"]}
			</InputNumber>
			<InputNumber
				min={-180}
				max={180}
				name="longitude"
				step="{0.000001}"
				inputmode="numeric"
				value="{settings.lon}"
			>
				{dict["longitude"]}
			</InputNumber>
			<GeolocationButton
				handleLocation={(lat, lon) => {
					settings.lat = lat;
					settings.lon = lon;
				}}
			/>
		</Fieldset>
		<Fieldset legend="Городское освещение">
			<InputRadio
				name="lights-city"
				options={LIGHTS_CITY_OPTIONS}
				value="{settings["lights-city"] ?? ""}"
			/>
		</Fieldset>
		<Fieldset className="{styles.submit}">
			<Button
				appearance="outline"
				type="submit"
				color="success"
			>
				{dict["save"]}
			</Button>
			<Button
				appearance="outline"
				on:click="{handleReset}"
				type="button"
			>
				{dict["reset"]}
			</Button>
		</Fieldset>
	</Form>
</div>
