// packages/photo-companion/src/shared/ui/input-datetime/input-datetime.tsx
import { splitProps } from "solid-js";
import { classnames } from "utils";
import { incrementDateByDay } from "utils/date";
import { isNullable } from "utils/validators";

import type { JSX } from "solid-js";

import { Button } from "../button/button";
import { IconChevronLeft, IconChevronRight, IconTimeline } from "../icons";

import styles from "./input-datetime.module.css";

export interface InputDatetimeProps extends JSX.InputHTMLAttributes<HTMLInputElement> {
	labels?: {
		DATETIME: string;
		NEXT_DAY: string;
		NOW: string;
		PREVIOUS_DAY: string;
	};
	onDatetimeChange?: (value: string) => void;
}

export function getDatetimeString(date = new Date()): string {
	const timezoneOffset = date.getTimezoneOffset() * 60000;
	return (new Date(date.getTime() - timezoneOffset)).toISOString().slice(0, 16);
}

export function InputDatetime(allProps: InputDatetimeProps) {
	const [ props, rest ] = splitProps(allProps, [
		"class",
		"children",
		"labels",
		"onChange",
		"onDatetimeChange"
	]);

	let inputRef: Undefinable<HTMLInputElement>;

	const handleReset = () => {
		props.onDatetimeChange?.(getDatetimeString());
	};

	const handleIncrement = (event: Event) => {
		const target = event.target as HTMLButtonElement;
		const step = Number(target.dataset.step);
		const value = inputRef?.value;

		if (!isNullable(value)) {
			const nextValue = getDatetimeString(incrementDateByDay(value, step));
			props.onDatetimeChange?.(nextValue);
		}
	};

	const handleChange = (event: Event) => {
		const target = event.target as HTMLButtonElement;
		props.onDatetimeChange?.(target.value);
	};

	return (
		<form class={classnames(styles.form, props.class)}>
			<Button
				class={styles["button-increment"]}
				data-step={-1}
				onClick={handleIncrement}
				title={props.labels?.PREVIOUS_DAY ?? "Previous day"}
				type="button"
			>
				<IconChevronLeft />
			</Button>
			<div class={styles["input-wrapper"]}>
				<label class={styles.label}>
					{props.children}
					<input
						aria-label={props.labels?.DATETIME ?? "Date and time"}
						class={styles.input}
						onChange={handleChange}
						ref={inputRef}
						type="datetime-local"
						{...rest}
					/>
				</label>
				<Button
					class={styles.button}
					onClick={handleReset}
					title={props.labels?.NOW ?? "Now"}
					type="button"
				>
					<IconTimeline />
				</Button>
			</div>
			<Button
				class={styles["button-increment"]}
				data-step={1}
				onClick={handleIncrement}
				title={props.labels?.NEXT_DAY ?? "Next day"}
				type="button"
			>
				<IconChevronRight
				/>
			</Button>
		</form>
	);
}

// src/deprecated/ui-svelte/src/components/input-date/input-datetime.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";
	import { classnames } from "utils";
	import { incrementDateByDay } from "utils/date";

	import { getDatetimeString } from "./input-datetime.helpers";
	import { iconTimeline, iconChevronLeft, iconChevronRight } from "../../icons";
	import Button from "../button/button.svelte";
	import Icon from "../icon/icon.svelte";
	import styles from "./input-datetime.module.css";

	interface Dict {
		DATETIME: string;
		NEXT_DAY: string;
		PREVIOUS_DAY: string;
	}

	export let className: Undefinable<string> = undefined;
	export let dict: Dict;
	export let max: Undefinable<string> = undefined;
	export let min: Undefinable<string> = undefined;
	export let title: Undefinable<string> = undefined;
	export let value = getDatetimeString();

	const dispatch = createEventDispatcher();

	const handleReset = () => {
		value = getDatetimeString();
		dispatch("datechange", { value });
	};

	const handleClick = (event: Event) => {
		const target = event.target as HTMLButtonElement;
		const step = Number(target.dataset.step);
		value = getDatetimeString(incrementDateByDay(value, step));
		dispatch("datechange", { value });
	};

	const handleChange = (event: Event) => {
		const target = event.target as HTMLButtonElement;
		value = target.value;
		dispatch("datechange", { value });
	};
</script>

<form on:submit|preventDefault class="{classnames(styles.form, className)}">
	<Button
		className="{styles["button-increment"]}"
		data-step="-1"
		on:click="{handleClick}"
		title="{dict.NEXT_DAY}"
	>
		<Icon
			viewBox="0 0 256 256"
			path="{iconChevronLeft}" 
		/>
	</Button>
	<div class="{styles["input-wrapper"]}">
		<label class="{styles.label}">
			<slot />
			<input
				aria-label="{dict.DATETIME}"
				class="{styles.input}"
				{max}
				{min}
				on:change="{handleChange}"
				{title}
				type="datetime-local"
				{value}
				{...$$restProps}
			/>
		</label>
		<Button
			className="{styles.button}"
			on:click="{handleReset}"
			title="Сейчас"
		>
			<Icon path="{iconTimeline}" />
		</Button>
	</div>
	<Button
		className="{styles["button-increment"]}"
		data-step="1"
		on:click="{handleClick}"
		title="{dict.PREVIOUS_DAY}"
	>
		<Icon
			viewBox="0 0 256 256"
			path="{iconChevronRight}"
		/>
	</Button>
</form>
