// src/packages/ui/src/components/input-text/input-text.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./input-text.module.css";

	export let className: string | undefined = undefined;
	export let inputmode: Undefinable<"numeric" | "text"> = undefined;
	export let maxlength: Undefinable<number> = undefined;
	export let minlength: Undefinable<number> = undefined;
	export let name: Undefinable<string> = undefined;
	export let pattern: Undefinable<string> = undefined;
	export let placeholder: Undefinable<string> = undefined;
	export let readonly = false;
	export let required = false;
	export let size: Undefinable<number> = undefined;
	export let spellcheck = false;
	export let value = "";
</script>

<label class="{classnames(styles.label, className)}">
	<slot />
	<input
		bind:value
		class="{styles.input}"
		{maxlength}
		{minlength}
		{name}
		on:input
		{pattern}
		{placeholder}
		{readonly}
		{required}
		{size}
		{spellcheck}
		type="text"
		{inputmode}
		{...$$restProps}
	/>
</label>

// src/core/ui-solid/src/components/input-text/input-text.tsx
import { splitProps  } from "solid-js";
import { classnames } from "utils";

import type { InputTextProps } from "./input-text.types";
import styles from "./input-text.module.css";

export function InputText(allProps: InputTextProps) {
	const [ props, rest ] = splitProps(allProps, [ "class", "children" ]);

	return (
		<label class={classnames(styles.label, props.class)}>
			{props.children}
			<input
				class="{styles.input}"
				type="text"
				{...rest}
			/>
		</label>
	);
}
