// src/apps/photo-companion-solid/src/lib/components/elevation-graph/pointer.tsx
import { createMemo, mergeProps } from "solid-js";

import { setAttribute } from "@lib/helpers";
import { useLocation } from "@lib/hooks";
import { createObjectCoordsGetter } from "./elevation-graph.helpers";
import type { AltitudeGetter } from "./elevation-graph.types";
import styles from "./elevation-graph.module.css";

interface Props {
	date: Date;
	getAltitude: AltitudeGetter;
	pointerSize?: number;
}

const DEFAULT_PROPS = {
	pointerSize: 6
};

export function GraphPointer(allProps: Props) {
	const props = mergeProps(DEFAULT_PROPS, allProps);
	const { latitude, longitude } = useLocation();

	const getPosition = () => createObjectCoordsGetter(props.getAltitude);
	const position = createMemo(() => {
		return getPosition()(props.date, latitude(), longitude());
	});

	return (
		<circle
			class={styles.pointer}
			data-above={setAttribute(position().y >= 0)}
			cx={position().x}
			cy={position().y}
			r={props.pointerSize}
		/>
	);
}

// src/apps/photo-companion/src/lib/components/elevation-graph/pointer.svelte
<svelte:options namespace="svg" />

<script lang="ts">
	import { settingsStore as store } from "@lib/stores";
	import { createObjectCoordsGetter } from "./elevation-graph.helpers";
	import { setAttribute } from "@lib/helpers";
	import type { AltitudeGetter } from "./elevation-graph.types";
	import styles from "./elevation-graph.module.css";

	export let date: Date;
	export let getAltitude: AltitudeGetter;
	export let pointerSize = 6;

	const getPosition = createObjectCoordsGetter(getAltitude);

	$: position = getPosition(date, $store.latitude, $store.longitude);
</script>

<circle
	class="{styles.pointer}"
	data-above="{setAttribute(position.y >= 0)}"
	cx="{position.x}"
	cy="{position.y}"
	r="{pointerSize}"
/>
