// src/core/ui-solid/src/components/input-radio/input-radio.tsx
import { splitProps, Index } from "solid-js";
import { classnames } from "utils";

import type { InputRadioProps } from "./input-radio.types";
import styles from "./input-radio.module.css";

export function InputRadio(allProps: InputRadioProps) {
	const [ props, rest ] = splitProps(allProps, [
		"class",
		"children",
		"options",
		"value"
	]);

	return (
		<Index each={props.options}>
			{item => (
				<label class={classnames(styles.label, props.class)}>
					{props.children}
					<input
						class={styles.radio}
						checked={props.value === item().value}
						disabled={item().disabled}
						type="radio"
						value={item().value}
						{...rest}
					/>
				</label>
			)}
		</Index>
	);
}

// src/apps/photo-companion/src/lib/components/input-radio/input-radio.svelte
<script lang="ts" context="module">
	export interface Option {
		label: string;
		value: string;
	}
</script>

<script lang="ts">
	import type { ChangeEventHandler } from "svelte/elements";
	import styles from "./input-radio.module.css";

	export let disabled = false;
	export let name: string;
	export let options: Option[] = [];
	export let value: Optional<string>;

	const handleChange: ChangeEventHandler<HTMLElement> = (event) => {
		const target = event.target as HTMLInputElement;
		value = target.value;
	};
</script>

{#each options as option}
	<label class="{styles.label}">
		<input
			class="{styles.radio}"
			{disabled}
			{name}
			on:change="{handleChange}"
			type="radio"
			value="{option.value}"
		/>
		<span />
		{option.label}
	</label>
{/each}
