// src/packages/ui/src/components/button/button.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./button.module.css";

	export let className: string | undefined = undefined;
	export let disabled = false;
	export let appearance: "ghost" | "fill" | "outline" = "fill";
	export let color: Nullable<"success" | "danger"> = undefined;
	export let type: HTMLButtonElement["type"] = "button";
</script>

<button
	class="{classnames(styles.button, className)}"
	data-appearance="{appearance}"
	data-color="{color}"
	{disabled}
	on:click
	{type}
	{...$$restProps}
>
	<slot />
</button>

// src/core/ui/src/components/button/button.tsx
import { mergeProps, splitProps } from "solid-js";
import { classnames } from "utils";

import type { ButtonProps } from "./button.types";

import styles from "./button.module.css";

const DEFAULT_PROPS: ButtonProps = {
	appearance: "fill",
	loading: false,
	type: "button"
};

export function Button(allProps: ButtonProps) {
	const mergedProps = mergeProps(DEFAULT_PROPS, allProps);
	const [ props, rest ] = splitProps(mergedProps, [
		"appearance",
		"children",
		"class",
		"icon",
		"loading",
		"variant"
	]);

	return (
		<button
			class={classnames(styles.button, props.class)}
			data-appearance={props.appearance}
			data-icon={props.icon ? "" : undefined}
			data-loading={props.loading ? "" : undefined}
			data-variant={props.variant}
			{...rest}
		>
			{props.children}
		</button>
	);
}
