// src/deprecated/ui-svelte/src/components/link/Link.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./link.module.css";

	export let block = false;
	export let className: Undefinable<string> = undefined;
	export let current: Undefinable<"page" | "step" | "location" | "date" | "time"> = undefined;
	export let download: undefined | string = undefined;
	export let href: string;
	export let label: Undefinable<string> = undefined;
	export let targetBlank = false;
	export let nofollow = false;
	export let title: Undefinable<string> = undefined;

	let ref: Nullish<HTMLAnchorElement> = null;

	// if no `href` is provided -> link will be disabled
	$: external = href.indexOf("://") !== -1;
	$: target = (targetBlank || external) ? "_blank" : undefined;
	$: rel = `${external ? "noopener noreferrer" : ""}` + `${nofollow ? "nofollow" : ""}`;
</script>

<a
	bind:this="{ref}"
	class="{classnames(styles.link, className)}"
	class:block
	aria-current="{current}"
	aria-label="{label}"
	{download}
	{href}
	on:click
	{rel}
	{target}
	{title}
	{...$$restProps}
>
	<slot />
</a>

// src/core/ui-solid/src/components/link/link.tsx
import { classnames } from "utils";
import { splitProps } from "solid-js";

import type { LinkProps } from "./link.types";
import styles from "./link.module.css";

export function Link(allProps: LinkProps) {
	const [ props, rest ] = splitProps(allProps, [
		"class",
		"children",
		"href",
		"nofollow",
		"targetBlank"
	]);

	const external = () => props.href?.indexOf("://") !== -1;
	const target = () => (props.targetBlank || external()) ? "_blank" : undefined;
	const rel = () => (
		`${external() ? "noopener noreferrer" : ""}` +
		`${props.nofollow ? "nofollow" : ""}`
	);

	return (
		<a
			class={classnames(styles.link, props.class)}
			href={props.href}
			target={target()}
			rel={rel()}
			{...rest}
		>
			{props.children}
		</a>
	);
}
