// packages/photo-companion/src/pages/timeline/timeline.page.tsx
import { For, Show } from "solid-js";
import { incrementDateByDay } from "utils/date";

import type { EventGroupName } from "types";

import { Timeline, TimelineEvent, TimelineEventEmpty, TimelineGroup } from "~/components";
import { useDatetime } from "~/hooks";
import { CityLightsProvider } from "~/services/city-lights";
import { useSettings } from "~/services/settings";
import { useTranslation } from "~/services/translation";
import { IconWarning } from "~/shared/ui/icons";

import { useDisabledTimeline, useTimelineEvents } from "./hooks";

import type { EventsProps } from "./timeline.types";

import styles from "./timeline.module.css";

const createEventLink = (type: EventGroupName) => {
	if (type === "BRIDGE") {
		return "/bridges";
	}

	return `/${type.toLowerCase()}`;
};

function NoEvents() {
	const { t } = useTranslation();

	return (
		<article class={styles.warning}>
			<h2>{t().MESSAGE.EVENTS_ARE_DISABLED}</h2>
			<IconWarning />
		</article>
	);
}

function Events(props: EventsProps) {
	const { format } = useTranslation();

	return (
		<TimelineGroup>
			<For each={props.timeline}>
				{({ date, items }) => (
					<Timeline date={format().date(date)}>
						<For each={items} fallback={<TimelineEventEmpty />}>
							{event => <TimelineEvent event={event} href={createEventLink(event.type)} />}
						</For>
					</Timeline>
				)}
			</For>
		</TimelineGroup>
	);
}

function EventTimeline() {
	const { getDatetime } = useDatetime();
	const { settings } = useSettings();
	const { getTimeline } = useTimelineEvents();
	const disabled = useDisabledTimeline();

	const timeline = () => {
		const tomorrow = incrementDateByDay(getDatetime(), 1);

		return [
			{
				date: getDatetime(),
				items: getTimeline(getDatetime(), settings.latitude, settings.longitude)
			},
			{
				date: tomorrow,
				items: getTimeline(tomorrow, settings.latitude, settings.longitude)
			}
		];
	};

	return (
		<div class={styles.page}>
			<Show fallback={<NoEvents />} when={disabled}>
				<Events timeline={timeline()} />
			</Show>
		</div>
	);
}

export const PageTimeline = () => (
	<CityLightsProvider>
		<EventTimeline />
	</CityLightsProvider>
);

export default PageTimeline;

// src/apps/photo-companion/src/pages/timeline/timeline.page.svelte
<script lang="ts" context="module">
	import type { TimelineEvent } from "@shared/types";

	interface TimelineEntry {
		date: Date;
		items: TimelineEvent[];
	}
</script>

<script lang="ts">
	import { Datetime, TimelineGroup, Timeline, Event, EventEmpty } from "@lib/components";
	import { initTimelineProvider } from "@services/events";
	import { incrementDateByDay } from "@shared/utils";
	import { settingsStore as store } from "@lib/settings-store";
	import { Link, Icon } from "@lib/components";
	import { iconWarning } from "@lib/icons";
	import styles from "./timeline.module.css";

	export let date: Date;

	const hasNoEvents = () => {
		return [
			$store.events_bridges_spb,
			$store.events_lights,
			$store.events_moon,
			$store.events_sun
		].every(check => !check);
	};

	const timelineProvider = initTimelineProvider({
		bridgeEvents: $store.events_bridges_spb,
		lightsEvents: $store.events_lights,
		moonEvents: $store.events_moon,
		sunEvents: $store.events_sun,
		predicate: event => event.timestamp >= date.getTime()
	});

	let timeline: TimelineEntry[] = [];

	$: {
		const tomorrow = incrementDateByDay(date, 1);

		timeline = [
			{
				date: date,
				items: timelineProvider.getEvents(date, $store.latitude, $store.longitude)
			},
			{
				date: tomorrow,
				items: timelineProvider.getEvents(tomorrow, $store.latitude, $store.longitude)
			}
		];
	}
</script>

<div class="{styles.page}">
	{#if hasNoEvents()}
		<article class="{styles.warning}">
			<h2>Все типы событий отключены</h2>
			<Icon path="{iconWarning}" />
			<p>
				Изменить настройки можно <Link href="/settings#event-blacklist">тут</Link>
			</p>
		</article>
	{:else}
		<TimelineGroup>
			{#each timeline as { date, items } (date.getTime())}
				<Timeline>
					<svelte:fragment slot="date">
						<Datetime
							{date}
							options={{
								year: "numeric",
								month: "long",
								day: "numeric" 
							}}
						/>
					</svelte:fragment>
					{#each items as event (`${event.timestamp}/${event.name}`)}
						<Event {event} />
					{:else}
						<EventEmpty />
					{/each}
				</Timeline>
			{/each}
		</TimelineGroup>
	{/if}
</div>
