// src/deprecated/photo-companion-svelte/src/lib/components/card-info/card-info.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./card-info.module.css";

	export let className: Undefinable<string> = undefined;
	export let data: Record<string, string | number> = {};
</script>

<article class="{classnames(styles.card, className)}">
	<dl>
		{#each Object.entries(data) as [ property, value ]}
			<div class="{styles.entry}">
				<dt>{property}</dt>
				<dd class="{styles.value}">{value}</dd>
			</div>
		{/each}
	</dl>
</article>

// packages/photo-companion/src/entities/card-info/ui/card-info/card-info.tsx
import { type ParentProps, Show } from "solid-js";
import { classnames } from "utils";

import styles from "./card-info.module.css";

interface CardInfoProps extends ParentProps {
	classes?: {
		card?: string;
		list?: string;
		title?: string;
	};
	title?: string;
}

export const CardInfo = (props: CardInfoProps) => (
	<article class={classnames(styles.card, props.classes?.card)}>
		<Show when={props.title}>
			{title => (
				<header class={classnames(styles.title, props.classes?.title)}>
					{title()}
				</header>
			)}
		</Show>
		<dl class={props.classes?.list}>
			{props.children}
		</dl>
	</article>
);
