// src/apps/photo-companion-solid/src/lib/components/card-bridge/card-bridge.tsx
import { getBridgeScheduleEntry, getBridgeState } from "bridge-schedule";
import { Show, createMemo, createSignal } from "solid-js";
import { Icon } from "ui-solid";
import { iconWarning } from "ui-solid/icons";

import { t } from "@lib/stores/lang";
import { Countdown } from "../countdown";
import type { BridgeName } from "types";
import { BridgeSparkline } from "./card-bridge-sparkline";
import styles from "./card-bridge.module.css";

interface Props {
	exception?: boolean;
	name: BridgeName;
}

export function CardBridge(props: Props) {
	const schedule = () => getBridgeScheduleEntry(props.name);
	const [ getDate, setDate ] = createSignal(new Date());
	const state = createMemo(() => getBridgeState(props.name, getDate(), true));

	return (
		<article class={styles.card}>
			<header>
				<h2>
					{t().BRIDGE_NAME_SPB[props.name]} {t().LABEL.BRIDGE}
					<Show when={props.exception}>
						<Icon
							path={iconWarning}
							title={t().MESSAGE.BRIDGE_EXCEPTION}
						/>
					</Show>
				</h2>
				<output>
					<Show when={state().open} fallback={t().LABEL.BRIDGE_CLOSED}>
						{t().LABEL.BRIDGE_OPENED}
					</Show>
				</output>
			</header>
			<BridgeSparkline schedule={schedule()} />
			<footer>
				<p>
					<Show when={state().open} fallback={t().MESSAGE.BRIDGE_WILL_OPEN_WITHIN}>
						{t().MESSAGE.BRIDGE_WILL_CLOSE_WITHIN}
					</Show>
				</p>
				<Countdown
					initialTimestamp={state().timestamp}
					callback={() => {
						setDate(new Date());
						return state().timestamp;
					}}
				/>
			</footer>
		</article>
	);
}

// src/lib/components/card-bridge/card-bridge.svelte
<script lang="ts">
	import ScheduleSparkline from "./card-bridge-sparkline.svelte";
	import Timer from "../timer/timer.svelte";
	import Icon from "../icon/icon.svelte";
	import { getBridgeStateByDate, getBridgeSchedule } from "@services/bridges";
	import { iconWarning } from "@lib/icons";
	import { dict, template } from "@lib/dict";
	import type { BridgeName, BridgeShedule } from "@lib/types";
	import styles from "./card-bridge.module.css";

	export let name: BridgeName;
	export let exception = false;
	
	let schedule: BridgeShedule = getBridgeSchedule(name);
	let state = getBridgeStateByDate(name, new Date(), true);
</script>

{#if state}
	<article class="{styles.card}">
		<header>
			<h2>
				{dict[name]} {dict["bridge"]}
				{#if exception}
				<Icon
					path="{iconWarning}"
					title="{dict["bridge-exception"]}"
				/>
		{/if}
			</h2>
			<output>
				{state.open
					? dict["bridge-opened"]
					: dict["bridge-closed"]}
			</output>
		</header>
		<div>
			
		</div>
		<ScheduleSparkline
			{schedule}
		/>
		<footer>
			<p>{template["bridge-next-event"](state.open)}</p>
			<Timer
				timestamp={state.timestamp}
				on:alarm="{() => {
					state = getBridgeStateByDate(name, new Date(), true);
				}}"
			/>
		</footer>
	</article>
{/if}
