// src/apps/photo-companion-solid/src/lib/components/elevation-graph/path.tsx
import { isSameDay } from "utils/date";

import { useLocation } from "@lib/hooks";
import { createPathBuilder } from "./elevation-graph.helpers";
import type { AltitudeGetter } from "./elevation-graph.types";
import styles from "./elevation-graph.module.css";
import { createMemo } from "solid-js";

interface Props {
	date: Date;
	getAltitude: AltitudeGetter;
}

const MEMO_OPTIONS = {
	equals: (prev: Date, next: Date) => isSameDay(prev, next)
};

export function GraphPath(props: Props) {
	const { latitude, longitude } = useLocation();

	const buildPath = () => createPathBuilder(props.getAltitude);

	const path = createMemo(() => {
		return buildPath()(props.date, latitude(), longitude());
	}, MEMO_OPTIONS);

	return (
		<path
			class={styles.graph}
			d={path()}
		/>
	);
}

// src/deprecated/photo-companion-svelte/src/lib/components/elevation-graph/path.svelte
<svelte:options namespace="svg" />

<script lang="ts">
	import { isSameDay } from "utils/date";

	import { settingsStore as store } from "@lib/stores";
	import { createPathBuilder } from "./elevation-graph.helpers";
	import type { AltitudeGetter } from "./elevation-graph.types";
	import styles from "./elevation-graph.module.css";

	export let date: Date;
	export let getAltitude: AltitudeGetter;

	const buildPath = createPathBuilder(getAltitude);
	let lastDate = new Date(date);
	let path = buildPath(date, $store.latitude, $store.longitude);

	$: {
		// no need to build a path for the same date
		if (!isSameDay(date, lastDate)) {
			path = buildPath(date, $store.latitude, $store.longitude);
			lastDate = new Date(date);
		}
	}
</script>

<path
	class="{styles.graph}"
	d="{path}"
/>
