// src/apps/photo-companion-solid/src/lib/components/gauge/gauge-time.tsx
import type { ParentProps } from "solid-js";

import { formatTimeShort } from "@stores/lang";
import { Gauge } from "./gauge";
import { getAngleFromTime } from "@lib/helpers";

interface Props {
	date: Date;
	timeStart?: Date;
	timeEnd?: Date;
	pointerAngle?: number;
}

export function GaugeTime(props: ParentProps<Props>) {

	return (
		<Gauge
			angleStart={getAngleFromTime(props.timeStart)}
			angleEnd={getAngleFromTime(props.timeEnd)}
			labelStart={formatTimeShort(props.timeStart)}
			labelEnd={formatTimeShort(props.timeEnd)}
			pointerAngle={getAngleFromTime(props.date)}
		>
			{props.children}
		</Gauge>
	);
}

// src/lib/components/gauge/gauge-time.svelte
<script lang="ts">
	import Gauge from "./gauge.svelte";
	import { getAngleFromTime, formatTime } from "../../helpers";

	export let timeFrom: Date;
	export let timeTo: Date;
</script>

<Gauge
	angleStart={getAngleFromTime(timeFrom)}
	labelStart="{formatTime(timeFrom.getTime())}"
	angleEnd={getAngleFromTime(timeTo)}
	labelEnd="{formatTime(timeTo.getTime())}"
	{...$$restProps}
>
	<slot />
</Gauge>
