// packages/photo-companion/src/pages/settings/ui/input-geolocation/geolocation.tsx
import { useTranslation } from "~/features/translation";
import { Input } from "~/shared/ui";

import { FORM_INPUT_NAME } from "../../consts";
import { useSettingsForm } from "../../settings.context";
import { GeolocationButton } from "./geolocation-button";

export function InputGeolocation() {
	const { t } = useTranslation();
	const { settingsStore } = useSettingsForm();

	return (
		<>
			<Input
				inputmode="numeric"
				max={90}
				min={-90}
				name={FORM_INPUT_NAME.LATITUDE}
				step="any"
				type="number"
				value={settingsStore.latitude}
			>
				{t().LABEL.LATITUDE}
			</Input>
			<Input
				inputmode="numeric"
				max={180}
				min={-180}
				name={FORM_INPUT_NAME.LONGITUDE}
				step="any"
				type="number"
				value={settingsStore.longitude}
			>
				{t().LABEL.LONGITUDE}
			</Input>
			<GeolocationButton />
		</>
	);
}

// src/apps/photo-companion-solid/src/routes/settings/components/input-geolocation/geolocation.tsx
import { InputNumber } from "ui-solid";

import type { SetStoreFunction, Store } from "solid-js/store";

import { type SettingsStore, useTranslation } from "@lib/context";

import { GeolocationButton } from "./geolocation-button";

interface Props {
	setStore: SetStoreFunction<SettingsStore>;
	store: Store<SettingsStore>;
}

export function InputGeolocation(props: Props) {
	const { t } = useTranslation();

	return (
		<>
			<InputNumber
				inputmode="numeric"
				max={90}
				min={-90}
				name="latitude"
				step={0.000000000001}
				value={props.store.latitude}
			>
				{t().LABEL.LATITUDE}
			</InputNumber>
			<InputNumber
				inputmode="numeric"
				max={180}
				min={-180}
				name="longitude"
				step={0.000000000001}
				value={props.store.longitude}
			>
				{t().LABEL.LONGITUDE}
			</InputNumber>
			<GeolocationButton
				handleLocation={(latitude, longitude) => {
					props.setStore({ latitude, longitude });
				}}
			/>
		</>
	);
}
