// src/apps/photo-companion/src/lib/layout/with-date/with-date.tsx
import { InputDatetime } from "ui";

import type { ParentProps } from "solid-js";

import { useTranslation } from "@lib/context";
import { getDateTimeString, parseDateTimeString } from "@lib/helpers";
import { useDatetime } from "@lib/hooks";

import styles from "./with-date.module.css";

export function WithDate(props: ParentProps) {
	const { getDatetime, setDatetimeQuery } = useDatetime();
	const { t } = useTranslation();

	const value = () => getDateTimeString(getDatetime());

	const handleDatetimeChange = (input: string) => {
		setDatetimeQuery(parseDateTimeString(input));
	};

	const dict = () => {
		const tr = t();

		return {
			DATETIME: tr.LABEL.DATETIME,
			NEXT_DAY: tr.LABEL.NEXT_DAY,
			NOW: tr.LABEL.NOW,
			PREVIOUS_DAY: tr.LABEL.PREVIOUS_DAY
		};
	};

	return (
		<>
			{props.children}
			<InputDatetime
				class={styles["date-input"]}
				dict={dict()}
				onDatetimeChange={handleDatetimeChange}
				value={value()}
			/>
		</>
	);
}

// src/apps/photo-companion/src/lib/layout/with-date/with-date.svelte
<script lang="ts">
	import { query } from "svelte-pathfinder";
	import { InputDatetime } from "ui";
	import { isValidDate } from "utils/validators";

	import ErrorDate from "../../../pages/error-date/error-date.svelte";
	import { parseQueryDate, createQueryDate } from "@lib/helpers";
	import { onMount } from "svelte";
	import styles from "./with-date.module.css";
	import { dict } from "@lib/dict";

	let value = parseQueryDate($query.date as string);
	let date = new Date(value);

	const handleChange = (event: CustomEvent<{ value: string }>) => {
		date = new Date(event.detail.value);
		$query.date = createQueryDate(date);
	};

	query.hook(($updated) => {
		if (!$updated) {
			return false;
		}

		value = parseQueryDate($updated.date as string);
		date = new Date(value);
	});

	onMount(() => {
		if (!$query.date) {
			$query.date = createQueryDate();
		}
	});
</script>

{#if !isValidDate(date)}
	<ErrorDate />
{:else}
	<slot {date} />
{/if}

<InputDatetime
	className="{styles["date-input"]}"
	dict="{{
		DATETIME: dict.LABEL.DATETIME,
		NEXT_DAY: dict.LABEL.NEXT_DAY,
		PREVIOUS_DAY: dict.LABEL.PREVIOUS_DAY
	}}"
	on:datechange="{handleChange}"
	{value}
/>
