// packages/photo-companion/src/layout/with-date/with-date.tsx
import type { ParentProps } from "solid-js";

import { useDatetime } from "~/features/datetime-query";
import { useTranslation } from "~/features/translation";
import { InputDatetime } from "~/shared/ui";

import { getDateTimeString, parseDateTimeString } from "./helpers";

import styles from "./with-date.module.css";

export function WithDate(props: ParentProps) {
	const { getDatetime, setDatetimeQuery } = useDatetime();
	const { t } = useTranslation();

	const value = () => getDateTimeString(getDatetime());

	const handleDatetimeChange = (input: string) => {
		setDatetimeQuery(parseDateTimeString(input));
	};

	return (
		<>
			{props.children}
			<InputDatetime
				class={styles["date-input"]}
				labels={{
					DATETIME: t().LABEL.DATETIME,
					NEXT_DAY: t().LABEL.NEXT_DAY,
					NOW: t().LABEL.NOW,
					PREVIOUS_DAY: t().LABEL.PREVIOUS_DAY
				}}
				onDatetimeChange={handleDatetimeChange}
				value={value()}
			/>
		</>
	);
}

// src/apps/photo-companion/src/lib/layout/with-date/with-date.svelte
<script lang="ts">
	import { query } from "svelte-pathfinder";
	import { InputDatetime } from "ui";
	import { isValidDate } from "@shared/utils";
	import ErrorDate from "../../../pages/error-date/error-date.svelte";
	import { parseQueryDate, createQueryDate } from "@lib/helpers";
	import { onMount } from "svelte";
	import styles from "./with-date.module.css";
	import { dict } from "@lib/dict";

	let value = parseQueryDate($query.date as string);
	let date = new Date(value);

	const handleChange = (event: CustomEvent<{ value: string }>) => {
		date = new Date(event.detail.value);
		$query.date = createQueryDate(date);
	};

	query.hook(($updated) => {
		if (!$updated) {
			return false;
		}

		value = parseQueryDate($updated.date as string);
		date = new Date(value);
	});

	onMount(() => {
		if (!$query.date) {
			$query.date = createQueryDate();
		}
	});
</script>

{#if !isValidDate(date)}
	<ErrorDate />
{:else}
	<slot {date} />
{/if}

<InputDatetime
	className="{styles["date-input"]}"
	dict="{{
		DATETIME: dict.LABEL.DATETIME,
		NEXT_DAY: dict.LABEL.NEXT_DAY,
		PREVIOUS_DAY: dict.LABEL.PREVIOUS_DAY
	}}"
	on:datechange="{handleChange}"
	{value}
/>
