// src/apps/photo-companion-solid/src/routes/bridges/components/next-bridge-event/next-bridge-event.tsx
import { getNextBridgeEvent } from "bridge-schedule";
import { createMemo, createSignal } from "solid-js";
import { classnames } from "utils";

import { Countdown } from "@lib/components";
import { t } from "@stores/lang";
import styles from "./next-bridge-event.module.css";

export function NextBridgeEvent() {
	const [ getDate, setDate ] = createSignal<number>(Date.now());
	const state = createMemo(() => getNextBridgeEvent(new Date(getDate())));

	const getNextTimestamp = () => {
		setDate(Date.now());
		return state().timestamp;
	};

	return (
		<article class={classnames("card", styles["next-event-info"])}>
			<header>
				<h2>{t().TITLE.THE_CLOSEST_EVENT}</h2>
			</header>
			<p>
				{t().BRIDGE_SPB_EVENTS[`${state().name}_${!state().open ? "OPEN" : "CLOSE"}`]}
			</p>
			<Countdown
				initialTimestamp={state().timestamp}
				callback={getNextTimestamp}
			/>
		</article>
	);
}

// src/deprecated/photo-companion-svelte/src/pages/bridges/next-bridge-event.svelte
<script lang="ts">
	import { getNextBridgeEvent } from "bridge-schedule";
	import { TimerDigits } from "@lib/components";
	import { t } from "@stores/lang";
	import styles from "./bridges.module.css";

	let state = getNextBridgeEvent(new Date());
</script>

<article class="card {styles["next-event-info"]}">
	<header>
		<h2>{$t.TITLE.THE_CLOSEST_EVENT}</h2>
	</header>
	<p>
		{$t.BRIDGE_SPB_EVENTS[`${state.name}_${!state.open ? "OPEN" : "CLOSE"}`]}
	</p>
	<TimerDigits
		timestamp={state.timestamp}
		on:alarm="{() => {
			state = getNextBridgeEvent(new Date());
		}}"
	/>
</article>
