// src/apps/photo-companion/src/lib/components/gauge/gauge-label.svelte
<svelte:options namespace="svg" />

<script lang="ts">
	import { polarToCartesian } from "./gauge.helpers";
	import styles from "./gauge.module.css";

	export let angle = 0;
	export let label: string | undefined = undefined;
	export let radius: number;
</script>

<text
	class="{styles.label}"
	x="{polarToCartesian(0, 0, radius, angle).x}"
	y="{polarToCartesian(0, 0, radius, angle).y}"
	transform={angle > 180 ? `rotate(${angle - 270})` : `rotate(${angle - 90})`}
	transform-origin="center"
	dominant-baseline="central"
>
	{label}
</text>

// packages/photo-companion/src/entities/gauge/ui/gauge-label/gauge-label.tsx
import { type JSX, mergeProps } from "solid-js";

import { polarToCartesian } from "../../lib";

interface Props extends JSX.SvgSVGAttributes<SVGTextElement> {
	angle?: number;
	label?: string;
	radius: number;
}

const DEFAULT_PROPS = {
	angle: 0
};

export function Label(allProps: Props) {
	const props = mergeProps(DEFAULT_PROPS, allProps);

	const coords = () => polarToCartesian(0, 0, props.radius, props.angle);
	const transform = () => props.angle > 180
		? `rotate(${props.angle - 270})`
		: `rotate(${props.angle - 90})`;

	return (
		<text
			{...coords()}
			dominant-baseline="central"
			transform={transform()}
			transform-origin="center"
		>
			{props.label}
		</text>
	);
}
