// src/apps/photo-companion-solid/src/lib/components/navigation/navigation.tsx
import { Icon, Link } from "ui-solid";

import { navigation, getTabData } from "@lib/stores/navigation";
import { scrollToTop } from "@lib/helpers";
import { NavigationRoute } from "@lib/stores/navigation/navigation.types";
import { t } from "@stores/lang";
import { For } from "solid-js";

import styles from "./navigation.module.css";

function NavigationItem(props: NavigationRoute) {

	return (
		<li>
			<Link
				class={styles.link}
				href={props.href}
				onClick={scrollToTop}
			>
				<Icon
					class={styles.icon}
					path={props.icon}
					viewBox="0 0 256 256"
				/>
				<span>{t().TITLE[props.label]}</span>
			</Link>
		</li>
	);
}

export function Navigation() {

	return (
		<nav
			class={styles.navigation}
			style={{
				"--navigation-items-count": navigation().length
			}}
		>
			<ul class={styles["nav-items"]}>
				<For each={navigation()}>
					{item => <NavigationItem {...getTabData(item)} />}
				</For>
			</ul>
		</nav>
	);
}

// src/deprecated/photo-companion-svelte/src/lib/layout/navigation/navigation.svelte
<script lang="ts">
	import { path, query } from "svelte-pathfinder";
	import { Icon, Link } from "ui";

	import { t } from "@stores/lang";
	import { navigationStore, getTabData } from "@lib/stores/navigation";
	import { scrollToTop } from "@lib/helpers";
	import styles from "./navigation.module.css";
</script>

<nav
	class="{styles.navigation}"
	style="--navigation-items-count: {$navigationStore.length}"
>
	<ul class="{styles["nav-items"]}">
		{#each $navigationStore as tab}
			{@const { label, href, icon } = getTabData(tab)}
			<li>
				<Link
					current="{href.includes($path[0]) ? "page" : undefined}"
					className="{styles.link}"
					href="{href}{$query}"
					on:click="{scrollToTop}"
				>
					<Icon
						className="{styles.icon}"
						path="{icon}"
						viewBox="0 0 256 256"
					/>
					<span>{$t.TITLE[label]}</span>
				</Link>
			</li>
		{/each}
	</ul>
</nav>
