// src/packages/ui/src/components/details/details.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./details.module.css";

	export let className: string | undefined = undefined;
	export let open = false;
	export let title: Undefinable<string> = undefined;
</script>

<details bind:open class="{classnames(styles.details, className)}">
	<summary class="{styles.summary}">
		<span class={`ellipsis ${styles.title}`}>
			{#if title}
				{title}
			{:else}
				<slot name="title">
					Title was not defined
				</slot>
			{/if}
		</span>
		<slot name="icon">
			<svg class={styles["icon"]} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
				<polygon points="21.11 5.5 12 15.72 2.89 5.5 2 7.28 12 18.5 22 7.28 21.11 5.5" />
			</svg>
		</slot>
	</summary>
	<div class={styles.content}>
		<slot />
	</div>
</details>

// packages/photo-companion/src/shared/ui/details/details.tsx
import { type JSX, splitProps } from "solid-js";
import { classnames } from "utils";

import type { Classes } from "../../types";

import styles from "./details.module.css";

export interface DetailsProps extends JSX.DetailsHtmlAttributes<HTMLDetailsElement> {
	classes?: Classes<"content" | "details" | "label" | "summary">;
	label: string;
}

const DetailsIcon = () => (
	<svg class={styles.icon} viewBox="0 0 24 24">
		<polygon points="21.11 5.5 12 15.72 2.89 5.5 2 7.28 12 18.5 22 7.28 21.11 5.5" />
	</svg>
);

export function Details(allProps: DetailsProps) {
	const [ props, rest ] = splitProps(allProps, [
		"classes",
		"children",
		"label",
		"title"
	]);

	return (
		<details class={classnames(styles.details, props.classes?.details)} {...rest}>
			<summary class={classnames(styles.summary, props.classes?.summary)}>
				<span class={classnames("ellipsis", styles.title, props.classes?.label)}>
					{props.label}
				</span>
				<DetailsIcon />
			</summary>
			<div class={classnames(styles.content, props.classes?.content)}>
				{props.children}
			</div>
		</details>
	);
}
