// src/lib/layout/navigation/navigation.svelte
<script lang="ts">
	import { pattern, query } from "svelte-pathfinder";
	import { Icon, Link } from "@lib/components";
	import { dict } from "@lib/dict";
	import { iconTimeline, iconLights, iconSun, iconMoon } from "@lib/icons";
	import { routeLights, routeMoon, routeSun, routeTimeline } from "@lib/routes";
	import styles from "./navigation.module.css";

	const sections = [
		{ label: "timeline", href: routeTimeline, icon: iconTimeline, root: true },
		{ label: "lights", href: routeLights, icon: iconLights },
		{ label: "sun", href: routeSun, icon: iconSun },
		{ label: "moon", href: routeMoon, icon: iconMoon }
	];
</script>

<nav class="{styles.navigation}">
	<ul>
		{#each sections as { label, href, icon, root }}
			<li>
				<Link
					current="{($pattern(href) || ($pattern("/") && root)) ? "page" : undefined}"
					className="{styles.link}"
					href="{href}?date={$query.date}"
				>
					<Icon path="{icon}" viewBox="0 0 256 256" />
					{dict[label]}
				</Link>
			</li>
		{/each}
	</ul>
</nav>

// src/apps/photo-companion-solid/src/lib/components/navigation/navigation.tsx
import { For } from "solid-js";
import { Icon, Link } from "ui-solid";

import { navigation, getTabData, type NavigationRoute } from "@lib/stores/navigation";
import { t } from "@stores/lang";

import styles from "./navigation.module.css";
import { useMatch } from "@solidjs/router";

function NavigationItem(props: NavigationRoute) {
	const match = useMatch(() => props.href);

	return (
		<li>
			<Link
				aria-current={match() ? "page" : undefined}
				class={styles.link}
				href={props.href}
			>
				<Icon
					class={styles.icon}
					path={props.icon}
					viewBox="0 0 256 256"
				/>
				<span>{t().TITLE[props.label]}</span>
			</Link>
		</li>
	);
}

export const Navigation = () => (
	<nav
		class={styles.navigation}
		style={{ "--navigation-items-count": navigation().length }}
	>
		<ul class={styles["nav-items"]}>
			<For each={navigation()}>
				{item => <NavigationItem {...getTabData(item)} />}
			</For>
		</ul>
	</nav>
);
