// packages/photo-companion/src/shared/ui/input-radio/input-radio.tsx
import { Index, type JSX, splitProps } from "solid-js";
import { classnames } from "utils";

import type { Classes } from "../../types";

import styles from "./input-radio.module.css";

export interface InputRadioOption {
	disabled?: boolean,
	label: string;
	selected?: boolean;
	value: string;
}

export interface InputRadioProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "class"> {
	classes?: Classes<"indicator" | "input" | "label" | "root">;
	options: InputRadioOption[];
}

export function InputRadio(allProps: InputRadioProps) {
	const [ props, rest ] = splitProps(allProps, [
		"classes",
		"children",
		"options",
		"value"
	]);

	return (
		<Index each={props.options}>
			{item => (
				<label class={classnames(styles.root, props.classes?.root)}>
					<input
						checked={props.value === item().value}
						class={classnames(styles.radio, props.classes?.input)}
						disabled={item().disabled}
						type="radio"
						value={item().value}
						{...rest}
					/>
					<span class={classnames(styles.indicator, props.classes?.indicator)} />
					<span class={classnames(styles.label, props.classes?.label)}>
						{item().label}
					</span>
				</label>
			)}
		</Index>
	);
}

// src/deprecated/ui-svelte/src/components/input-radio/input-radio.svelte
<script lang="ts" context="module">
	export interface Option {
		label: string;
		value: string;
	}
</script>

<script lang="ts">
	import type { ChangeEventHandler } from "svelte/elements";
	import { classnames } from "utils";

	import styles from "./input-radio.module.css";

	export let className: Undefinable<string> = undefined;
	export let disabled = false;
	export let name: string;
	export let options: Option[] = [];
	export let value: Undefinable<string>;

	const handleChange: ChangeEventHandler<HTMLElement> = (event) => {
		const target = event.target as HTMLInputElement;
		value = target.value;
	};
</script>

{#each options as option}
	<label class="{classnames(styles.label, className)}">
		<input
			class="{styles.radio}"
			checked="{value === option.value}"
			{disabled}
			{name}
			on:change="{handleChange}"
			type="radio"
			value="{option.value}"
		/>
		<span />
		{option.label}
	</label>
{/each}
