// src/apps/photo-companion-solid/src/lib/components/timeline-event/event.tsx
import { Time, Link } from "ui-solid";

import { formatTimeShort, formatDatetime, type Translation, t } from "@lib/stores/lang";
import { lightsEventComponent } from "./timeline-event-lights";
import { bridgeEventComponent } from "./timeline-event-bridge";
import { sunEventComponent } from "./timeline-event-sun";
import { moonEventComponent } from "./timeline-event-moon";

import {
	isBridgeEvent,
	isLightsEvent,
	isMoonEvent,
	isSunEvent
} from "@lib/helpers/validators";

//import { createQueryDate } from "@lib/helpers";
import type { TimelineEvent } from "types";
import styles from "./event.module.css";
import type { Accessor } from "solid-js";
import { Dynamic } from "solid-js/web";
import { Show } from "solid-js";

const eventComponent = (event: TimelineEvent, t: Accessor<Translation>) => {
	if (isBridgeEvent(event)) {
		return bridgeEventComponent(event, t());
	}

	if (isLightsEvent(event)) {
		return lightsEventComponent(event, t());
	}

	if (isMoonEvent(event)) {
		return moonEventComponent(event, t());
	}

	if (isSunEvent(event)) {
		return sunEventComponent(event, t());
	}

	throw new Error(`Unknown event is provided: ${JSON.stringify(event)}`);
};

interface EventProps {
	page?: string;
	event: TimelineEvent;
	secondary?: boolean;
}

export function TimelineEvent(props: EventProps) {
	const data = () => eventComponent(props.event, t);
	const linkTitle = () => `${data().title}: ${formatDatetime(new Date(props.event.timestamp))}`;

	return (
		<li
			class={styles.event}
			//aria-current={props.current ? "date" : undefined}
			aria-secondary={props.secondary ? "" : undefined}
			data-event-name={props.event.name}
		>
			<Time>
				{formatTimeShort(props.event.timestamp)}
			</Time>
			<div class={styles.icon} data-event-icon>
				<Link
					class={styles.link}
					href="/"
					title={linkTitle()}
				>
					<Dynamic component={data().component} {...data().props} />
				</Link>
			</div>
			<article>
				<p>{data().title}</p>
				<Show when={data().message}>
					{message => <p>{message()}</p>}
				</Show>
			</article>
		</li>
	);
}

// src/apps/photo-companion/src/lib/components/event/event.svelte
<script lang="ts">
	import { query } from "svelte-pathfinder";
	import { Datetime, Link } from "ui";

	import { formatDatetime } from "@stores/locale";
	import { lightsEventComponent } from "./event.lights";
	import { bridgeEventComponent } from "./event.bridge";
	import { sunEventComponent } from "./event.sun";
	import { moonEventComponent } from "./event.moon";
	import { isBridgeEvent, isLightsEvent, isMoonEvent, isSunEvent } from "@lib/helpers/validators";
	import { createQueryDate } from "@lib/helpers";
	import type { TimelineEvent } from "types";
	import styles from "./event.module.css";

	// when need event reference for another page, usually secondary
	export let page: Undefinable<string> = undefined;
	export let event: TimelineEvent;
	export let secondary = false;

	let current = false;
	let dateQuery = createQueryDate(new Date(event.timestamp));

	const eventComponent = (event: TimelineEvent) => {
		if (isBridgeEvent(event)) {
			return bridgeEventComponent(event);
		}

		if (isLightsEvent(event)) {
			return lightsEventComponent(event);
		}

		if (isMoonEvent(event)) {
			return moonEventComponent(event);
		}

		if (isSunEvent(event)) {
			return sunEventComponent(event);
		}

		throw new Error(`Unknown event is provided: ${JSON.stringify(event)}`);
	};

	let { component, props, message, title, type } = eventComponent(event);
	let linkTitle = `${title}: ${formatDatetime(new Date(event.timestamp))}`;

	$: {
		if ($query.date) {
			current = ($query.date === dateQuery);
		} else {
			current = false;
		}
	}
</script>

<li
	class="{styles.event}"
	aria-current="{current ? "date" : undefined}"
	data-secondary="{secondary ? "" : undefined}"
	data-event-name="{event.name}"
>
	<Datetime
		date="{new Date(event.timestamp)}"
		options={{
			hour12: false,
			hour: "2-digit",
			minute: "2-digit"
		}}
	/>
	<div class="{styles.icon}" data-event-icon>
		<Link
			className="{styles.link}"
			href="/{page ?? type ?? ""}?{new URLSearchParams({ ...$query, date: dateQuery }).toString()}"
			title="{linkTitle}"
		>
			<svelte:component
				this="{component}"
				{...props}
			/>
		</Link>
	</div>
	<article>
		<p>{title}</p>
		{#if message}
			<p>{message}</p>
		{/if}
	</article>
</li>
