// src/deprecated/ui-svelte/src/components/input-select/input-select.svelte
<script lang="ts" context="module">
	export interface InputSelectOption {
		disabled?: boolean,
		label: string;
		value: string;
		selected?: boolean;
	}
</script>

<script lang="ts">
	import { classnames } from "utils";

	import styles from "./input-select.module.css";

	export let className: Undefinable<string> = undefined;
	export let disabled = false;
	export let name: string;
	export let options: InputSelectOption[];
	export let value: Undefinable<string> = undefined;

	if (!value) {
		value = options.find(item => Boolean(item.selected))?.value;
	}
</script>

<label class="{classnames(styles.wrapper, className)}">
	<slot />
	<select
		bind:value
		class="{styles.select}"
		{disabled}
		{name}
		on:change
	>
		{#each options as { disabled, value, label, selected }}
			<option {value} {selected} {disabled}>
				{label}
			</option>
		{/each}
	</select>
</label>

// src/core/ui-solid/src/components/input-select/input-select.tsx
import { For, splitProps } from "solid-js";
import { classnames } from "utils";

import type { InputSelectProps } from "./input-select.types";

import styles from "./input-select.module.css";

export function InputSelect(allProps: InputSelectProps) {
	const [ props, rest ] = splitProps(allProps, [ "class", "children", "options" ]);

	return (
		<label class={classnames(styles.label, props.class)}>
			{props.children}
			<select class={styles.select} {...rest}>
				<For each={props.options}>
					{({ label, ...other }) => (
						<option {...other}>
							{label}
						</option>
					)}
				</For>
			</select>
		</label>
	);
}
