// src/apps/photo-companion/src/lib/layout/navigation/navigation.svelte
<script lang="ts">
	import { query } from "svelte-pathfinder";
	import { Icon, Link } from "ui";

	import { dict } from "@lib/dict";
	import { navigationStore } from "@lib/stores";
	import { scrollToTop } from "@lib/helpers";
	import styles from "./navigation.module.css";
</script>

<nav
	class="{styles.navigation}"
	style="--navigation-items-count: {$navigationStore.length}"
>
	<ul class="{styles["nav-items"]}">
		{#each $navigationStore as { label, href, icon, current }}
			<li>
				<Link
					current="{current ? "page": undefined}"
					className="{styles.link}"
					href="{href}{$query}"
					on:click="{scrollToTop}"
				>
					<Icon
						className="{styles.icon}"
						path="{icon}"
						viewBox="0 0 256 256"
					/>
					<span>{dict.TITLE[label]}</span>
				</Link>
			</li>
		{/each}
	</ul>
</nav>

// src/apps/photo-companion/src/lib/components/navigation/navigation.tsx
import { useMatch } from "@solidjs/router";
import { For } from "solid-js";
import { Dynamic } from "solid-js/web";

import { useTranslation } from "@lib/context";
import { useNavigationTabs } from "@lib/hooks";

import { LinkQuery } from "../link-query";

import type { NavigationRoute } from "./navigation.types";

import styles from "./navigation.module.css";

function NavigationItem(props: NavigationRoute) {
	const match = useMatch(() => props.href);
	const { t } = useTranslation();

	return (
		<li>
			<LinkQuery
				aria-current={match() ? "page" : undefined}
				class={styles.link}
				href={props.href}
			>
				<Dynamic class={styles.icon} component={props.Icon} />
				<span>{t().TITLE[props.label]}</span>
			</LinkQuery>
		</li>
	);
}

export function Navigation() {
	const { getTabLinks } = useNavigationTabs();

	return (
		<nav
			class={styles.navigation}
			style={{ "--navigation-items-count": getTabLinks().length }}
		>
			<ul class={styles["nav-items"]}>
				<For each={getTabLinks()}>
					{item => <NavigationItem {...item} />}
				</For>
			</ul>
		</nav>
	);
}
