// src/apps/photo-companion-solid/src/lib/components/card-info/card-info.tsx
import { For, type JSXElement } from "solid-js";
import { objectEntries } from "utils";

import styles from "./card-info.module.css";

interface Props {
	data: Record<string, string | number>
}

interface CardEntry {
	property: string;
	value: JSXElement;
}

const CardEntry = (props: CardEntry) => (
	<div class={styles.entry}>
		<dt>
			{props.property}
		</dt>
		<dd class={styles.value}>
			{props.value}
		</dd>
	</div>
);

export const CardInfo = (props: Props) => (
	<article class={styles.card}>
		<dl>
			<For each={objectEntries(props.data)}>
				{item => (
					<CardEntry property={item[0]} value={item[1]} />
				)}
			</For>
		</dl>
	</article>
);

// src/deprecated/photo-companion-svelte/src/lib/components/card-info/card-info.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./card-info.module.css";

	export let className: Undefinable<string> = undefined;
	export let data: Record<string, string | number> = {};
</script>

<article class="{classnames(styles.card, className)}">
	<dl>
		{#each Object.entries(data) as [ property, value ]}
			<div class="{styles.entry}">
				<dt>{property}</dt>
				<dd class="{styles.value}">{value}</dd>
			</div>
		{/each}
	</dl>
</article>
