// src/apps/photo-companion/src/lib/components/card-bridge/card-bridge.svelte
<script lang="ts">
	import { getBridgeState, getBridgeScheduleEntry } from "bridge-schedule";
	import { Icon } from "ui";
	import { iconWarning } from "ui/icons";
	import type { BridgeName } from "types";

	import ScheduleSparkline from "./card-bridge-sparkline.svelte";
	import { TimerDigits } from "@lib/components";
	import { dict } from "@lib/dict";
	import styles from "./card-bridge.module.css";

	export let name: BridgeName;
	export let exception = false;
	
	let schedule = getBridgeScheduleEntry(name);
	let state = getBridgeState(name, new Date(), true);
</script>

{#if state}
	<article class="{styles.card}">
		<header>
			<h2>
				{dict.BRIDGE_NAME_SPB[name]} {dict.LABEL.BRIDGE}
				{#if exception}
				<Icon
					path="{iconWarning}"
					title="{dict.MESSAGE.BRIDGE_EXCEPTION}"
				/>
		{/if}
			</h2>
			<output>
				{
					state.open
						? dict.LABEL.BRIDGE_OPENED
						: dict.LABEL.BRIDGE_CLOSED
				}
			</output>
		</header>
		<div>
			
		</div>
		<ScheduleSparkline
			{schedule}
		/>
		<footer>
			<p>{
				state.open
					? dict.MESSAGE.BRIDGE_WILL_CLOSE_WITHIN
					: dict.MESSAGE.BRIDGE_WILL_OPEN_WITHIN
				}
			</p>
			<TimerDigits
				timestamp={state.timestamp}
				on:alarm="{() => {
					state = getBridgeState(name, new Date(), true);
				}}"
			/>
		</footer>
	</article>
{/if}

// src/apps/photo-companion-solid/src/routes/bridges/components/card-bridge/card-bridge.tsx
import { getBridgeScheduleEntry, getBridgeState } from "bridge-schedule";
import { Show, createMemo, createSignal } from "solid-js";
import { Icon } from "ui-solid";
import { iconWarning } from "ui-solid/icons";

import { Countdown } from "@lib/components";
import { t } from "@lib/stores/lang";
import type { BridgeName } from "types";
import { BridgeSparkline } from "./card-bridge-sparkline";
import styles from "./card-bridge.module.css";

interface Props {
	exception?: boolean;
	name: BridgeName;
}

export function CardBridge(props: Props) {
	const schedule = () => getBridgeScheduleEntry(props.name);
	const [ getDate, setDate ] = createSignal(new Date());
	const state = createMemo(() => getBridgeState(props.name, getDate(), true));

	return (
		<article class={styles.card}>
			<header>
				<h2>
					{t().BRIDGE_NAME_SPB[props.name]} {t().LABEL.BRIDGE}
					<Show when={props.exception}>
						<Icon
							path={iconWarning}
							title={t().MESSAGE.BRIDGE_EXCEPTION}
						/>
					</Show>
				</h2>
				<output>
					<Show when={state().open} fallback={t().LABEL.BRIDGE_CLOSED}>
						{t().LABEL.BRIDGE_OPENED}
					</Show>
				</output>
			</header>
			<BridgeSparkline schedule={schedule()} />
			<footer>
				<p>
					<Show when={state().open} fallback={t().MESSAGE.BRIDGE_WILL_OPEN_WITHIN}>
						{t().MESSAGE.BRIDGE_WILL_CLOSE_WITHIN}
					</Show>
				</p>
				<Countdown
					initialTimestamp={state().timestamp}
					callback={() => {
						setDate(new Date());
						return state().timestamp;
					}}
				/>
			</footer>
		</article>
	);
}
