// src/apps/photo-companion/src/lib/components/card-info/card-info.svelte
<script lang="ts">
	import styles from "./card-info.module.css";

	export let data: Record<string, string | number> = {};
</script>

<article class="{styles.card}">
	<dl>
		{#each Object.entries(data) as [ property, value ]}
			<div class="{styles.entry}">
				<dt>{property}</dt>
				<dd class="{styles.value}">{value}</dd>
			</div>
		{/each}
	</dl>
</article>

// src/apps/photo-companion/src/lib/components/card-info/card-info.tsx
import type { ParentProps } from "solid-js";

import styles from "./card-info.module.css";

interface CardEntry {
	property: string;
}

export const CardEntry = (props: ParentProps<CardEntry>) => (
	<div class={styles.entry}>
		<dt>
			{props.property}
		</dt>
		<dd class={styles.value}>
			{props.children}
		</dd>
	</div>
);

export const CardInfo = (props: ParentProps) => (
	<article class={styles.card}>
		<dl>
			{props.children}
		</dl>
	</article>
);
