// packages/photo-companion/src/routes/sun/sun-data.tsx
import { CardEntry, CardInfo } from "~/components";
import { useTranslation } from "~/services/translation";

import type { SunData as SunDataType } from "./use-sun-data";

interface SunDataProps {
	state: SunDataType;
}

export function SunData(props: SunDataProps) {
	const { t } = useTranslation();

	return (
		<CardInfo>
			<CardEntry property={t().LABEL.DURATION_DAYLIGHT}>
				{props.state.dayDuration}
			</CardEntry>
			<CardEntry property={t().LABEL.ALTITUDE}>
				{props.state.position.altitude}
			</CardEntry>
			<CardEntry property={t().LABEL.AZIMUTH}>
				{props.state.position.azimuth}
			</CardEntry>
			<CardEntry property={t().LABEL.DECLINATION}>
				{props.state.position.declination}
			</CardEntry>
			<CardEntry property={t().LABEL.ZENITH}>
				{props.state.position.zenith}
			</CardEntry>
		</CardInfo>
	);
}

// packages/photo-companion/src/pages/sun/ui/sun-data.tsx
import { Show } from "solid-js";

import { useSunService } from "~/features/sun";
import { useTranslation } from "~/features/translation";
import { PropertyList } from "~/shared/ui";

export function SunData(props: { title?: string }) {
	const { format, t } = useTranslation();
	const { altitude, azimuth, dayDuration, declination, sunrise, sunset, zenith } = useSunService();

	return (
		<PropertyList>
			<Show when={props.title}>
				<PropertyList.Header>
					{props.title}
				</PropertyList.Header>
			</Show>
			<PropertyList.Body>
				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.SUNRISE_TIME}</PropertyList.Label>
					<PropertyList.Value>{format().timeShort(sunrise())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.SUNSET_TIME}</PropertyList.Label>
					<PropertyList.Value>{format().timeShort(sunset())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.DURATION_DAYLIGHT}</PropertyList.Label>
					<PropertyList.Value>{format().timeDuration(dayDuration())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.ALTITUDE}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(altitude())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.AZIMUTH}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(azimuth())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.DECLINATION}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(declination())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.ZENITH}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(zenith())}</PropertyList.Value>
				</PropertyList.Item>
			</PropertyList.Body>
		</PropertyList>
	);
}
