// packages/photo-companion/src/pages/sun/components/sun-data.tsx
import { CardEntry, CardInfo } from "~/components";
import { useSunService } from "~/features/sun";
import { useTranslation } from "~/features/translation";

export function SunData(props: { title?: string }) {
	const { format, t } = useTranslation();
	const { altitude, azimuth, dayDuration, declination, sunrise, sunset, zenith } = useSunService();

	return (
		<CardInfo title={props.title}>
			<CardEntry property={t().LABEL.SUNRISE_TIME}>
				{format().timeShort(sunrise())}
			</CardEntry>
			<CardEntry property={t().LABEL.SUNSET_TIME}>
				{format().timeShort(sunset())}
			</CardEntry>
			<CardEntry property={t().LABEL.DURATION_DAYLIGHT}>
				{format().timeDuration(dayDuration())}
			</CardEntry>
			<CardEntry property={t().LABEL.ALTITUDE}>
				{format().degrees(altitude())}
			</CardEntry>
			<CardEntry property={t().LABEL.AZIMUTH}>
				{format().degrees(azimuth())}
			</CardEntry>
			<CardEntry property={t().LABEL.DECLINATION}>
				{format().degrees(declination())}
			</CardEntry>
			<CardEntry property={t().LABEL.ZENITH}>
				{format().degrees(zenith())}
			</CardEntry>
		</CardInfo>
	);
}

// packages/photo-companion/src/pages/sun/ui/sun-data.tsx
import { Show } from "solid-js";

import { useSunService } from "~/features/sun";
import { useTranslation } from "~/features/translation";
import { PropertyList } from "~/shared/ui";

export function SunData(props: { title?: string }) {
	const { format, t } = useTranslation();
	const { altitude, azimuth, dayDuration, declination, sunrise, sunset, zenith } = useSunService();

	return (
		<PropertyList>
			<Show when={props.title}>
				<PropertyList.Header>
					{props.title}
				</PropertyList.Header>
			</Show>
			<PropertyList.Body>
				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.SUNRISE_TIME}</PropertyList.Label>
					<PropertyList.Value>{format().timeShort(sunrise())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.SUNSET_TIME}</PropertyList.Label>
					<PropertyList.Value>{format().timeShort(sunset())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.DURATION_DAYLIGHT}</PropertyList.Label>
					<PropertyList.Value>{format().timeDuration(dayDuration())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.ALTITUDE}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(altitude())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.AZIMUTH}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(azimuth())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.DECLINATION}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(declination())}</PropertyList.Value>
				</PropertyList.Item>

				<PropertyList.Item>
					<PropertyList.Label>{t().LABEL.ZENITH}</PropertyList.Label>
					<PropertyList.Value>{format().degrees(zenith())}</PropertyList.Value>
				</PropertyList.Item>
			</PropertyList.Body>
		</PropertyList>
	);
}
