// src/apps/photo-companion/src/routes/bridges/bridges.page.tsx
import { isBridgeException, SUPPORTED_BRIDGES_NAME_SET } from "bridge-schedule";
import { For } from "solid-js";
import { Button, IconChevronDown } from "ui";

import { useTranslation } from "@lib/context";

import { CardBridge, NavigationEvent, NextBridgeEvent } from "./components";

import styles from "./bridges.module.css";

const BridgeList = () => (
	<ul>
		<For each={Array.from(SUPPORTED_BRIDGES_NAME_SET)}>
			{name => (
				<li>
					<CardBridge
						exception={isBridgeException(name)}
						name={name}
					/>
				</li>
			)}
		</For>
	</ul>
);

export function PageBridges() {
	const { t } = useTranslation();

	return (
		<div class={styles.page}>
			<div>
				<h2 id="bridge-schedule">
					{t().TITLE.BRIDGES_SCHEDULE_SPB}
				</h2>
				<BridgeList />
			</div>
			<aside>
				<NavigationEvent />
				<NextBridgeEvent />
				<Button
					appearance="ghost"
					onClick={() => {
						document.querySelector("#bridge-schedule")
							?.scrollIntoView({
								behavior: "smooth"
							});
					}}
				>
					<IconChevronDown />
				</Button>
			</aside>
		</div>
	);
}

// src/apps/photo-companion/src/pages/bridges/bridges.page.svelte
<script lang="ts">
	import {SUPPORTED_BRIDGES_NAME_SET, isBridgeException } from "bridge-schedule";
	import { CardBridge, Icon, Button } from "@lib/components";
	import NextBridgeEvent from "./next-bridge-event.svelte";
	import NavigationEvent from "./navigation-event.svelte";
	import { iconChevronDown } from "@lib/icons";
	import { dict } from "@lib/dict";
	import styles from "./bridges.module.css";
</script>

<div class="{styles.page}">
	<div>
		<h2 id="bridge-schedule">
			{dict.TITLE.BRIDGES_SCHEDULE_SPB}
		</h2>
		<ul>
			{#each SUPPORTED_BRIDGES_NAME_SET as name}
				<li>
					<CardBridge
						{name}
						exception="{isBridgeException(name)}"
					/>
				</li>
			{/each}
		</ul>
	</div>
	<aside>
		<NextBridgeEvent />
		<NavigationEvent />
			<Button
				appearance="ghost"
				on:click="{() => {
					document.querySelector("#bridge-schedule")
						?.scrollIntoView({
							behavior: "smooth"
						});
				}}"
			>
				<Icon path="{iconChevronDown}" />
			</Button>
	</aside>
</div>
