// src/apps/photo-companion/src/router/routes.svelte
<script lang="ts">
	import Router from "./router.svelte";
	import Route from "./route.svelte";
	import { App, WithSwipe } from "@lib/layout";
	import { WithDateURL, Article } from "@lib/layout";

	import { default as PageAbout } from "../pages/about/about.page.mdx";
	import { default as PageBridges } from "../pages/bridges/bridges.page.svelte";
	import { default as PageChangelog } from "../pages/changelog.page.mdx";
	import { default as PageLights } from "../pages/lights/lights.page.svelte";
	import { default as PageMoon } from "../pages/moon/moon.page.svelte";
	import { default as PageSettings } from "../pages/settings/settings.page.svelte";
	import { default as PageSun } from "../pages/sun/sun.page.svelte";
	import { default as PageTimeline } from "../pages/timeline/timeline.page.svelte";
</script>

<Router root="{App}">
	<Route path="{[ "timeline", "lights", "sun", "moon", "bridges" ]}">
		<WithSwipe>
			<Route path="{[ "timeline", "lights", "sun", "moon" ]}">
				<WithDateURL let:date>
					<Route path="timeline" component="{PageTimeline}" props={{ date }} />
					<Route path="lights" component="{PageLights}" props={{ date }} />
					<Route path="sun" component="{PageSun}" props={{ date }} />
					<Route path="moon" component="{PageMoon}" props={{ date }} />
				</WithDateURL>
			</Route>
			<Route path="bridges" component="{PageBridges}" />
		</WithSwipe>
	</Route>
	<Route path="{[ "about", "changelog" ]}">
		<Article>
			<Route path="about" component="{PageAbout}" />
			<Route path="changelog" component="{PageChangelog}" />
		</Article>
	</Route>
	<Route path="settings" component="{PageSettings}" />
</Router>

// src/apps/photo-companion/src/routes/index.tsx
import { Route, Router } from "@solidjs/router";

import { ROUTE } from "@lib/consts";
import { Root } from "@lib/layout/root/root";
import { WithDate } from "@lib/layout/with-date/with-date";
import { WithSwipe } from "@lib/layout/with-swipe";

import { PageAbout } from "./about/about.page";
import { PageBridges } from "./bridges/bridges.page";
import { PageChangelog } from "./changelog/changelog.page";
import { PageLights } from "./lights/lights.page";
import { PageMoon } from "./moon/moon.page";
import { PageSettings } from "./settings/settings.page";
import { PageSun } from "./sun/sun.page";
import { PageTimeline } from "./timeline/timeline.page";

const WITH_DATE_ROUTES = [
	ROUTE.ROOT,
	ROUTE.TIMELINE,
	ROUTE.LIGHTS,
	ROUTE.MOON,
	ROUTE.SUN
];

const WITH_SWIPE_ROUTES = [ ...WITH_DATE_ROUTES, ROUTE.BRIDGES ];

export const Routes = () => (
	<Router root={Root}>
		<Route component={WithSwipe} path={WITH_SWIPE_ROUTES}>
			<Route component={WithDate} path={WITH_DATE_ROUTES}>
				<Route component={PageTimeline} path={[ ROUTE.ROOT, ROUTE.TIMELINE ]} />
				<Route component={PageLights} path={ROUTE.LIGHTS} />
				<Route component={PageMoon} path={ROUTE.MOON} />
				<Route component={PageSun} path={ROUTE.SUN} />
			</Route>
			<Route component={PageBridges} path={ROUTE.BRIDGES} />
		</Route>
		<Route component={PageSettings} path={ROUTE.SETTINGS} />
		<Route component={PageAbout} path={ROUTE.ABOUT} />
		<Route component={PageChangelog} path={ROUTE.CHANGELOG} />
	</Router>
);
