// src/deprecated/ui-svelte/src/components/input-radio/input-radio.svelte
<script lang="ts" context="module">
	export interface Option {
		label: string;
		value: string;
	}
</script>

<script lang="ts">
	import type { ChangeEventHandler } from "svelte/elements";
	import { classnames } from "utils";

	import styles from "./input-radio.module.css";

	export let className: Undefinable<string> = undefined;
	export let disabled = false;
	export let name: string;
	export let options: Option[] = [];
	export let value: Undefinable<string>;

	const handleChange: ChangeEventHandler<HTMLElement> = (event) => {
		const target = event.target as HTMLInputElement;
		value = target.value;
	};
</script>

{#each options as option}
	<label class="{classnames(styles.label, className)}">
		<input
			class="{styles.radio}"
			checked="{value === option.value}"
			{disabled}
			{name}
			on:change="{handleChange}"
			type="radio"
			value="{option.value}"
		/>
		<span />
		{option.label}
	</label>
{/each}

// src/core/ui/src/components/input-radio/input-radio.tsx
import { Index, splitProps } from "solid-js";
import { classnames } from "utils";

import type { InputRadioProps } from "./input-radio.types";

import styles from "./input-radio.module.css";

export function InputRadio(allProps: InputRadioProps) {
	const [ props, rest ] = splitProps(allProps, [
		"class",
		"children",
		"options",
		"value"
	]);

	return (
		<Index each={props.options}>
			{item => (
				<label class={classnames(styles.label, props.class)}>
					<input
						checked={props.value === item().value}
						class={styles.radio}
						disabled={item().disabled}
						type="radio"
						value={item().value}
						{...rest}
					/>
					<span />
					{item().label}
				</label>
			)}
		</Index>
	);
}
