// packages/photo-companion/src/shared/ui/button/button.tsx
import { mergeProps, splitProps } from "solid-js";
import { classnames, setAttribute } from "utils";

import type { JSX } from "solid-js";

import styles from "./button.module.css";

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
	appearance?: "fill" | "ghost" | "outline";
	icon?: boolean;
	pending?: boolean;
	variant?: Nullable<"danger" | "success">;
}

const DEFAULT_PROPS: ButtonProps = {
	appearance: "fill",
	pending: false,
	type: "button"
};

export function Button(allProps: ButtonProps) {
	const mergedProps = mergeProps(DEFAULT_PROPS, allProps);
	const [ props, rest ] = splitProps(mergedProps, [
		"appearance",
		"children",
		"class",
		"icon",
		"pending",
		"variant"
	]);

	return (
		<button
			class={classnames(styles.button, props.class)}
			data-appearance={props.appearance}
			data-icon={setAttribute(props.icon)}
			data-pending={setAttribute(props.pending)}
			data-variant={props.variant}
			{...rest}
		>
			{props.children}
		</button>
	);
}

// src/packages/ui/src/components/button/button.svelte
<script lang="ts">
	import { classnames } from "utils";

	import styles from "./button.module.css";

	export let className: string | undefined = undefined;
	export let disabled = false;
	export let appearance: "ghost" | "fill" | "outline" = "fill";
	export let color: Nullable<"success" | "danger"> = undefined;
	export let type: HTMLButtonElement["type"] = "button";
</script>

<button
	class="{classnames(styles.button, className)}"
	data-appearance="{appearance}"
	data-color="{color}"
	{disabled}
	on:click
	{type}
	{...$$restProps}
>
	<slot />
</button>
