// src/apps/photo-companion-solid/src/routes/settings/components/input-geolocation/geolocation-button.tsx
import { createSignal, onCleanup } from "solid-js";
import { Button } from "ui-solid";

import { t } from "@lib/stores/lang";
import { getUserLocation } from "@lib/helpers";

type Status = Nullish<"success" | "danger" | "loading">;

interface GeolocationButtonProps {
	handleLocation: (latitude: number, longitude: number) => void;
}

export function GeolocationButton(props: GeolocationButtonProps) {
	const MESSAGE = {
		loading: () => "loading",
		success: () => t().MESSAGE.DATA_UPDATE_SUCCESS,
		danger: () => t().MESSAGE.DATA_UPDATE_ERROR
	};

	const [ getState, setState ] = createSignal<Status>(null);

	const message = () => {
		const state = getState();
		return state ? MESSAGE[state]() : t().LABEL.ASK_DEVICE_GEOLOCATION;
	};

	const variant = () => {
		const state = getState();

		if (state !== "danger" && state !== "success") {
			return null;
		}

		return state;
	};

	let timerID: Undefinable<number> = undefined;
	onCleanup(() => clearInterval(timerID));

	const handleGetGeolocation = async () => {
		try {
			clearInterval(timerID);
			setState("loading");
			const position = await getUserLocation();

			if (position) {
				props.handleLocation(position.latitude, position.longitude);
				setState("success");
			}
		} catch (error) {
			console.warn(`Could not get location: ${JSON.stringify(error)}`);
			setState("danger");
		} finally {
			timerID = window.setTimeout(() => setState(null), 2500);
		}
	};

	return (
		<Button
			appearance="outline"
			variant={variant()}
			loading={getState() === "loading"}
			onClick={() => void handleGetGeolocation()}
		>
			{message()}
		</Button>
	);
}

// src/deprecated/photo-companion-svelte/src/pages/settings/geolocation-button.svelte
<script lang="ts">
	import { onDestroy } from "svelte";
	import { Button } from "ui";
	import { getUserLocation } from "@lib/helpers";
	import { t } from "@stores/lang";

	export let handleLocation: (lat: number, lon: number) => void;

	let disabled = false;
	let message = $t.LABEL.ASK_DEVICE_GEOLOCATION;
	let status: Nullable<"success" | "danger"> = undefined;
	let timer: Undefinable<number> = undefined;

	const handleResetState = () => {
		timer = window.setTimeout(() => {
			message = $t.LABEL.ASK_DEVICE_GEOLOCATION;
			status = undefined;
			disabled = false;
		}, 2500);
	};

	const handleGetGeolocation = async () => {
		try {
			disabled = true;
			message = "В процессе";
			const position = await getUserLocation();

			if (position) {
				handleLocation(position.lat, position.lon);
				status = "success";
				message = $t.MESSAGE.DATA_UPDATE_SUCCESS;
			}
		} catch (error) {
			console.warn(`Could not get location: ${JSON.stringify(error)}`);
			status = "danger";
			message = $t.MESSAGE.DATA_UPDATE_ERROR;
		} finally {
			handleResetState();
		}
	};

	onDestroy(() => {
		window.clearTimeout(timer);
	});
</script>

<Button
	appearance="outline"
	color="{status}"
	{disabled}
	on:click="{handleGetGeolocation}"
>
	{message}
</Button>
