// src/apps/photo-companion/src/pages/timeline/timeline.page.svelte
<script lang="ts" context="module">
	import type { TimelineEvent } from "@shared/types";

	interface TimelineEntry {
		date: Date;
		items: TimelineEvent[];
	}
</script>

<script lang="ts">
	import { Datetime, Link, Icon } from "ui";
	import { iconWarning } from "ui/icons";
	import { TimelineGroup, Timeline, Event, EventEmpty } from "@lib/components";
	import { initTimelineProvider } from "@services/events";
	import { incrementDateByDay } from "@shared/utils";
	import { settingsStore as store } from "@lib/stores";
	import styles from "./timeline.module.css";

	export let date: Date;

	const hasNoEvents = () => {
		return [
			$store.events_bridges_spb,
			$store.events_lights,
			$store.events_moon,
			$store.events_sun
		].every(check => !check);
	};

	const timelineProvider = initTimelineProvider({
		bridgeEvents: $store.events_bridges_spb,
		lightsEvents: $store.events_lights,
		moonEvents: $store.events_moon,
		sunEvents: $store.events_sun,
		predicate: event => event.timestamp >= date.getTime()
	});

	let timeline: TimelineEntry[] = [];

	$: {
		const tomorrow = incrementDateByDay(date, 1);

		timeline = [
			{
				date: date,
				items: timelineProvider.getEvents(date, $store.latitude, $store.longitude)
			},
			{
				date: tomorrow,
				items: timelineProvider.getEvents(tomorrow, $store.latitude, $store.longitude)
			}
		];
	}
</script>

<div class="{styles.page}">
	{#if hasNoEvents()}
		<article class="{styles.warning}">
			<h2>Все типы событий отключены</h2>
			<Icon path="{iconWarning}" />
			<p>
				Изменить настройки можно <Link href="/settings#event-blacklist">тут</Link>
			</p>
		</article>
	{:else}
		<TimelineGroup>
			{#each timeline as { date, items } (date.getTime())}
				<Timeline>
					<svelte:fragment slot="date">
						<Datetime
							{date}
							options={{
								year: "numeric",
								month: "long",
								day: "numeric" 
							}}
						/>
					</svelte:fragment>
					{#each items as event (`${event.timestamp}/${event.name}`)}
						<Event {event} />
					{:else}
						<EventEmpty />
					{/each}
				</Timeline>
			{/each}
		</TimelineGroup>
	{/if}
</div>

// src/apps/photo-companion-solid/src/routes/timeline/timeline.page.tsx
import { For, Show } from "solid-js";
import { Time, Icon } from "ui-solid";
import { iconWarning } from "ui-solid/icons";
import { incrementDateByDay } from "utils/date";

import { TimelineGroup, Timeline, TimelineEvent, TimelineEventEmpty } from "@lib/components";
import { settings } from "@stores/settings";
import { formatDate, t } from "@stores/lang";
import { useDatetime, useLocation } from "@lib/hooks";
import { hasSomeEvents } from "./timeline.helpers";
import { initTimelineProvider } from "../../services/events";
import type { EventsProps } from "./timeline.types";

import styles from "./timeline.module.css";

const NoEvents = () => (
	<article class={styles.warning}>
		<h2>{t().MESSAGE.EVENTS_ARE_DISABLED}</h2>
		<Icon path={iconWarning} />
	</article>
);

const Events = (props: EventsProps) => (
	<TimelineGroup>
		<For each={props.timeline}>
			{({ date, items }) => (
				<Timeline date={<Time>{formatDate(date)}</Time>}>
					<For each={items} fallback={<TimelineEventEmpty />}>
						{event => <TimelineEvent event={event} />}
					</For>
				</Timeline>
			)}
		</For>
	</TimelineGroup>
);

export function PageTimeline() {
	const { date } = useDatetime();
	const { latitude, longitude } = useLocation();

	const hasEvents = () => hasSomeEvents(settings());

	const provider = () => {
		const store = settings();
		const time = date().getTime();

		return initTimelineProvider({
			bridgeEvents: store.events_bridges_spb,
			lightsEvents: store.events_lights,
			moonEvents: store.events_moon,
			sunEvents: store.events_sun,
			predicate: (event) => event.timestamp >= time
		});
	};

	const timeline = () => {
		const tomorrow = incrementDateByDay(date(), 1);

		return [
			{
				date: date(),
				items: provider().getEvents(date(), latitude(), longitude())
			},
			{
				date: tomorrow,
				items: provider().getEvents(tomorrow, latitude(), longitude())
			}
		];
	};

	return (
		<div class={styles.page}>
			<Show when={hasEvents()} fallback={<NoEvents />}>
				<Events timeline={timeline()} />
			</Show>
		</div>
	);
}
